### ISSUE TITLE
Design specs for header search box pattern

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-design#10]
Create a pattern (maybe based on https://docs.ubuntu.com/maas/2.1/en/) for including a search input field in the header.

Ported from https://github.com/vanilla-framework/vanilla-framework/issues/922

**Comment by yaili** [comment]
@joanasa89 did you do something related to docs search box recently?

**Comment by joanasa89** [comment]
Yes, for docs.ubuntu.com (there is a bug on mobile, but is being fixed by Karl)
Designs are on dropbox https://www.dropbox.com/sh/i04zfjofded8khj/AADDPp6QxfatKxa1Leu5Womka?dl=0

**Comment by kwm14** [comment]
When designing we also need to consider the behaviour of the search component, originally documented [here](https://github.com/ubuntudesign/vanilla-design/issues/23):

[Notes from Vanilla brochure theme workshop](https://github.com/ubuntudesign/meeting-notes/issues/155):
- Agreed name: **search** (`p-search`)
- Needs design work:
  - Define behaviour, search icon and x icon placement, placeholder text and colour
  - Do we need to integrate auto-complete/live results?
  - Consider large variation (e.g. when used in the content area of a page of search results)
  - Consider how it works on different background colours (light, dark, …)

**Comment by kwm14** [comment]
## Review of header search box

- Review search boxes across our sites and applications
- Looking for consistent patterns in use
- Identify which parts work and don not

### ubuntu.com
![ubuntu](https://user-images.githubusercontent.com/17748020/34562238-5bef18c2-f145-11e7-881a-5923c9410e52.png)

### docs.ubuntu.com/maas
![maas-docs](https://user-images.githubusercontent.com/17748020/34562224-51f42fc4-f145-11e7-9a02-475705755e4d.png)

### jujucharms.com
![juju](https://user-images.githubusercontent.com/17748020/34562169-21dde082-f145-11e7-8af1-8d9b67ede2a8.png)

### docs.ubuntu.com
- updated and signed-off design by Joana
![docs ubuntu com](https://user-images.githubusercontent.com/17748020/34562282-856f6184-f145-11e7-8942-1f9b839b3237.png)

### snapcraft.io/discover
- not a header search box but still uses most recent Vanilla styling
![snapcraft io](https://user-images.githubusercontent.com/17748020/34562312-ad603510-f145-11e7-812a-58712a9741c4.png)

**Comment by kwm14** [comment]
Design and spec work scheduled [here](https://github.com/ubuntudesign/vanilla-and-base-squad/issues/156).
