### ISSUE TITLE
Post comments

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#100]
@kwm14 commented on [Wed Aug 09 2017](https://github.com/ubuntudesign/vanilla-squad/issues/41)

- could we use [disqus](https://disqus.com/)?
- do we allow/need threaded comments?

**Comment by kwm14** [comment]
@anthonydillon @barrymcgee is this issue more related to implementation/plugins rather than a design task?

**Comment by barrymcgee** [comment]
@kwm14 Has there been any decision on whether or not to use Disqus?

**Comment by kwm14** [comment]
@barrymcgee no decision has been made whether to use Disqus or not? @anthonydillon do you know if it has?

**Comment by pmahnke** [comment]
I haven't researched this at all, but I would prefer to use a hosted solution like disqus over anything homegrown.

I am happy to say we will use it if you guys like it

**Comment by kwm14** [comment]
@pmahnke ok great I've had a brief look at the website and there service looks good:

- it supports all devices from desktop to mobile, including Google AMP
- you can set it to your own styling so we have consistency across our sites

I'll create a new issue to research further into Disqus.
