### ISSUE TITLE
Accordion pattern may be either misnamed or misleadingly designed

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-design#105]
The existing [accordion pattern](https://docs.vanillaframework.io/en/patterns/accordion) present the user with **+** and **-** buttons. Presented with these buttons I would expect to be able to individually expand or collapse individual sections.

However, instead of this functionality, the functionality that's implemented in the docs is more inline with the naming - an "accordion". That is, when you click one of the **+** buttons, it closes the open section and opens that one instead. The **-** buttons simply do nothing.

To me, the design that would lead to me expecting the implemented behaviour would involve down and up arrows, instead of plus and minus buttons.

I suggest that we either:

- Rename this pattern to "Expand/collapse" or perhaps just "collapse" or "show/hide" or something, and change its implementation accordingly; or
- Change the design to use arrows instead, and in the example imeplementation, remove the arrow from the open section.

**Comment by kwm14** [comment]
- Update Javascript
- Rename?
- Modifier to trigger hide/show behaviour

**Comment by anthonydillon** [comment]
Who ever picks this up could you rename the accordion pattern and create a modifier or a new pattern named accordion so this change is backward compatibility. And, only changes the behaviour.

**Comment by kwm14** [comment]
Accordion has been fixed in v.1.7.0 but (+) and (-) will remain as it was a request previously made by Mark.
