### ISSUE TITLE
Design new panel pattern (card)

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-design#11]
Action from working group issue discussed here: https://github.com/vanilla-framework/vanilla-framework/issues/906

**Comment by yaili** [comment]
@kwm14 here is an example of an existing box with title for reference: https://www.ubuntu.com/cloud/contact-us

**Comment by yaili** [comment]
As part of this task we also need to define the name of the pattern — I don't think panel is clear enough

**Comment by yaili** [comment]
@kwm14 another example of a card with title/heading can be seen here in the "From prototype to production on all major platforms" section https://www.ubuntu.com/internet-of-things
and here in "Partners and players" https://www.ubuntu.com/internet-of-things/digital-signage

**Comment by kwm14** [comment]
## First iteration

- I've explored a few options taking influence from existing patterns seen on Ubuntu and our Cloud products MAAS and Juju.
- Each exploration has a version displaying just title, title and icon and a list item (accordion)
- We can review these in our working group this afternoon

### 001
![001-panel-pattern](https://cloud.githubusercontent.com/assets/17748020/25333003/8d514b3e-28e0-11e7-8ccf-35f966268ecf.png)

### 002
![002-panel-pattern](https://cloud.githubusercontent.com/assets/17748020/25333001/8d4cd676-28e0-11e7-88a6-254e4f4ab7b6.png)

### 003
![003-panel-pattern](https://cloud.githubusercontent.com/assets/17748020/25333002/8d5148d2-28e0-11e7-988c-96ef8f40bca8.png)

### 004
![004-panel-pattern](https://cloud.githubusercontent.com/assets/17748020/25333004/8d568586-28e0-11e7-954c-e164302f73eb.png)

**Comment by kwm14** [comment]
## Updated iteration

- taking all feedback into consideration from Visual review
- no background colour in heading
- solid divider, not dotted

### 005
![005-panel-pattern](https://cloud.githubusercontent.com/assets/17748020/25429072/b3e52604-2a6f-11e7-87ba-1f61f3277d86.png)

**Comment by yaili** [comment]
Great. I think we need to think of a better name for this. It's a variation of the card pattern. First idea:

- card heading

Any more?

@barrymcgee @anthonydillon @kwm14 @spencerbygraves ?

**Comment by anthonydillon** [comment]
It feels like the normal card but containing a header. We could expand the current card pattern to accommodate this but if not present in the markup. It just displays the content as a card. 

This would mean no new name or pattern. Just a little documentation to show the use cases.

**Comment by yaili** [comment]
Sounds good to me.

**Comment by yaili** [comment]
Added to code section
