### ISSUE TITLE
Table of contents with progress

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-design#114]
Check out the table of contents on the left.

https://www.which.co.uk/consumer-rights/advice/what-do-i-do-if-i-have-a-faulty-product

Should this be something we should introduce as a feature for the table of contents? 

Can this be applied to the current table of contents design (https://github.com/ubuntudesign/vanilla-design/blob/master/Aside/aside-nav.png) or would there need pattern need to be tweaked to accommodate the new progress?

**Comment by barrymcgee** [comment]
Note for consideration on email via @matthewpaulthomas :

> Heh. They forgot rule #1 of sticky layout: Make sure the element’s still
> usable when the viewport is shorter than the element. At 1280*800, I
> can’t even see the last four items in the table of contents until I’ve
> already scrolled to the end of the text.

**Comment by kwm14** [comment]
Reply from Mark in email chain:

> Your call on the design pattern for Vanilla, I was just sharing something I thought was interesting from a design perspective. What surprised me was that the movement on the side didn't seem as distracting as one would expect, instead it seems to create a nice impression of progress and position. I've seen similar cases where the ToC section heading highlight jumps as you scroll through the doc, and this seems smoother.

> So, make your own call :)

**Comment by anthonydillon** [comment]
From the working group, the consensus was that this pattern does now provide a benefit that outweighs the cost. Due to a large number of JavaScript event listeners (Scroll and resize). This is something that should be considered by UX and only adopted if there is a good use case.
