### ISSUE TITLE
Soft link colours for dark tooltips

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#115]
Pattern proposal/amendment

Proposal by @lyubomir-popov

Currently, soft links in dark tooltips are indistinguishable from text (white), which forces use of strong links (bold). Would be nice if they were a different colour (that satisfies AAA contrast ratio between text and background), based on the regular blue link colour/

## Is this a proposal or an amendment?

- Proposal

If amendment, what is the name of the pattern to be amended? Links

## Visual
![image](https://user-images.githubusercontent.com/2741678/31887607-e2c4cdc6-b7f0-11e7-9656-acce571f0be5.png)

new base colour: #54A7DF (current colour used on white background, adjusted to [meet AAA contrast requirements](https://webaim.org/resources/contrastchecker/) on #111 background)

Provide a screenshot or link to prototype of your pattern proposal.

## Context

On dark background, as in tooltips

## State

All current link states, adjusted to new values when used on dark background

## Progressive enhancement

No change

**Comment by kwm14** [comment]
Comment made by @spencerbygraves:

> As discussed in the patterns meeting, @lyubomir-popov will look at a blue also suitable for use on different coloured backgrounds such as takeovers and coloured strips.

**Comment by spencerbygraves** [comment]
From @matthewpaulthomas

links in tooltips
It would be confusing for tooltips to contain links, or anything else interactive, because that would prevent their usual behavior of disappearing when you move outside of the origin element. If there’s a different element that can contain interactive things, that’s fine, but it should have a different name and an obviously different appearance.

**Comment by kwm14** [comment]
Discussion on this proposal in Design patterns fortnightly, found in meeting notes [here](https://github.com/ubuntudesign/meeting-notes/issues/191):

**Extending button pattern and simple blue link**

  - We need a convention for setting link colours on all dark backgrounds
  - Also, need a proposal for use of tooltips. Light or dark tooltips, links in tooltips, etc
  - Been through many rounds of review previously, tricky subject
  - This is a lower priority and we'll revisit later.

**Comment by kwm14** [comment]
@lyubomir-popov @spencerbygraves revisiting some old issues from vanilla-design repo.

I know we still use tooltips in MAAS, Juju and Snappy and we haven't had any issues raised against the current implementation so wondered if this amendment still relevant in our Cloud applications?

**Comment by spencerbygraves** [comment]
@kwm14 @lyubomir-popov As @matthewpaulthomas says, I'm not sure we would have links in tooltips. Looking at this page, it's the difference between this:

![image](https://user-images.githubusercontent.com/9105999/46949813-989fd800-d07a-11e8-94b8-bdd637f47264.png)

And this:

![image](https://user-images.githubusercontent.com/9105999/46949842-ae150200-d07a-11e8-8417-938be8fbdc52.png)

So, I think we can close this.
