### ISSUE TITLE
Update design of code numbered

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#12]
Designs for [vanilla-framework issue 856](https://github.com/vanilla-framework/vanilla-framework/issues/856)

The purpose of adding some kind of visual division between line numbers and actual code is to make it more clear these are two different things, similar to what some code editors do.

There are 5 options here:

**v1: Current code block version**
![1-code block proposal current](https://cloud.githubusercontent.com/assets/223966/24045076/c30d081e-0b15-11e7-90f1-eccc975da302.png)

**v2: More space between line numbers and code**
![2-code block proposal nothing](https://cloud.githubusercontent.com/assets/223966/24045077/c3207994-0b15-11e7-945a-c84f49512412.png)

**v3: Vertical divider between line numbers and code, with white background**
![3-code block proposal divider](https://cloud.githubusercontent.com/assets/223966/24045079/c32c90c6-0b15-11e7-990b-9adfeb0d601b.png)

**v4: Background (cdcdcd) behind numbers (666666) - this was the initial suggestion, it's not accessible - could be accessible if the numbers are the same colour as text (111111)**
![4-code block proposal background](https://cloud.githubusercontent.com/assets/223966/24045080/c32c78b6-0b15-11e7-8c98-7f0deadcb056.png)

**v5: Background (cdcdcd) behind numbers (ffffff) - same comments as 4**
![5-code block proposal background reverse](https://cloud.githubusercontent.com/assets/223966/24045078/c3295d34-0b15-11e7-93da-0a1b64883e0a.png)

**Comment by yaili** [comment]
@spencerbygraves @kwm14 @joanasa89 @jamiedawsonyoung @alexubuntu would love your comments on this.

**Comment by joanasa89** [comment]
I think v3 works better (v4& v5 don't look accessible).

**Comment by kwm14** [comment]
+1 v3 too

- good space between line numbers and code
- vertical divider works well in splitting content
- neutral colour scheme has better contrast, more legible

**Comment by spencerbygraves** [comment]
Happy with v3. I think the border should be #CDCDCD. We seem to have both versions here - https://docs.vanillaframework.io/en/patterns/code-numbered

**Comment by jamiedawsonyoung** [comment]
V2 or V3 for me. 👍 

Only thing about V3 is the amount of bits (white block, grey divider, grey background, text colours different) to it and whether that's too much? All the code editors I have don't put a divider between the number and the code (I've only got 3 on my machine mind) Also I wonder if the emphasis is more on the code numbers than the text when the number column is white? Does it work reversed? 

Can we show a row highlight state for these or is that getting too complicated?

**Comment by yaili** [comment]
Good points, let me see if I can address them all:

- @spencerbygraves the outer border was changed from cdcdcd from feedback from docs team as there was not enough contrast between the border and the background to differentiate from code blocks. The initial proposal was to revert to dark background but we didn't want to do that.
- @jamiedawsonyoung I see what you mean… if we make the numbers light grey background and code white background, it won't be consistent with the normal code block which has light grey background
- It doesn't seem that more code editors have a different background colour for line numbers than not, but personally I do think they bring a sense of knowledge/documentation/order to a large code block

I have made a couple more examples based on the feedback. Let me know your thoughts! :)

**v6: Based on @jamiedawsonyoung's comment on emphasising the line numbers less**

![6-code block proposal divider reverse](https://cloud.githubusercontent.com/assets/223966/24050020/920a140e-0b25-11e7-9424-555395fd8cd4.png)

**v7: Variation on v6, without the divider line**

![7-code block proposal light background](https://cloud.githubusercontent.com/assets/223966/24050044/9ea4aaee-0b25-11e7-8f57-abe1768fa62f.png)

**Comment by jamiedawsonyoung** [comment]
V7 :-) Lovely

**Comment by spencerbygraves** [comment]
I don't think we should change the background colour yet again.

I still favour v3 with the correct border colour :)

**Comment by anthonydillon** [comment]
V3 is my fav too.

**Comment by yaili** [comment]
Based on feedback from design review, here is the latest version:

**v8: variation of v3 with all borders the same colour**

![8-code block proposal divider dark](https://cloud.githubusercontent.com/assets/223966/24166127/3a818f58-0e6a-11e7-9081-6743fee49b98.png)

**Comment by yaili** [comment]
@marcush could you have a look when you've got a moment? thanks 👍

**Comment by marcush** [comment]
I like v8 - variation of v3 
Although I do like v5 as well

**Comment by yaili** [comment]
@marcush thank you. In v4 and v5 the numbers aren't accessible though :(

**Comment by yaili** [comment]
Design spec updated: https://github.com/ubuntudesign/vanilla-design/tree/master/Code
