### ISSUE TITLE
Write content for downloads section

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#125]
Look at other design systems and see what they do:

- Carbon Design - http://carbondesignsystem.com/resources
- Apple - https://developer.apple.com/design/resources/
- Atlassian - https://atlassian.design/guidelines/marketing/resources/logo-files

**Comment by kwm14** [comment]
Once new content has been signed off I will add to vf.io copy doc [here](https://docs.google.com/document/d/1WQ3u4Eg9Vqp_yFBdIYUyGXkvhMxlPBMSr7g7O3rLzpg/edit#heading=h.wg87aglcdkt).

**v1**
### Downloads

**Vanilla Framework**
Download our simple CSS framework and design UI kit to include in your project. See the release notes for details on the latest updates.

_[ Download Vanilla Framework 1.6.2 ]_

**Vanilla Design**
A Sketch file of common design components.

_[ Download Vanilla Design UI Kit 1.6.2 ]_

**v2**
### Downloads

Download the Framework and UI kit to start designing and building with Vanilla Framework.

**Vanilla Framework**
_[ Start building with Vanilla Framework ]_

**Vanilla Design** 
_[ Download our Vanilla Design UI Kit as a Sketch file ]_

**v3**
### Downloads

Please find below some of the design resources and tools available to get started with Vanilla.

**_[ Vanilla Framework ]_**
Start building with our CSS Framework

**_[ Vanilla Design ]_**
Download our design library Sketch template

**Comment by spencerbygraves** [comment]
I think a combination of 1 & 2, here's my suggestion:

**Downloads**

Use our CSS framework and UI kit to start building your project. See the release notes for details on the latest updates.

[ Download Vanilla Framework 1.6.2 ]

[ Download our Vanilla Design UI Kit as a Sketch file ]

**Comment by pmahnke** [comment]
I like V1, how about.


## Downloads

### Vanilla Framework

Use our simple CSS framework and design UI kit in your project.
See the release notes for details on the latest updates.

[ Download Vanilla Framework 1.6.2 ](link)

### Vanilla Design

Get a Sketch file of common design components.

[ Download Vanilla Design UI Kit 1.6.2 ](link)

**Comment by spencerbygraves** [comment]
Thanks @pmahnke looks good to me.
