### ISSUE TITLE
Design slider component - Default

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#126]
Working GitHub [issue](https://github.com/ubuntudesign/vanilla-design/issues/22) discussing name and style of Slider.

**Comment by kwm14** [comment]
## Visual design

- Taking influence from ubuntu.com contribute page and JAAS deployment flow
- Slider control 16x16px
- Slider bar inherits component blue from Vanilla palette

### 001 
![default-slider-16px](https://user-images.githubusercontent.com/17748020/33208897-5c7b7326-d10b-11e7-8d7d-ee0effe37086.png)

**Comment by spencerbygraves** [comment]
@kwm14 Does it need to include a way to see the value?

**Comment by kwm14** [comment]
@spencerbygraves I wasn't sure whether to add a value as I thought this will need Javascript to work and we don't include this to Vanilla?

@anthonydillon do you know if this can be done with just HTML/CSS?

**Comment by anthonydillon** [comment]
@kwm14 It can be done but may require JS. Either way we may need to show the value.

By the way, the active colour should be `$color-accent` in Vanilla.

**Comment by kwm14** [comment]
@anthonydillon ok cool I will add a value input to the slider. For interactive components checkboxes, radio, switch etc we use `$color-information`

**Comment by anthonydillon** [comment]
Oh I see, thanks @kwm14

**Comment by kwm14** [comment]
## Visual design

- Updated design to include value (may require JS)
- Slider control toggle at 16px and 24px (explored both sizes as I didn't want the toggle and value input to compete with each-other)
- Value style inherits Vanilla input field component

### 002 @16px
![001-default-slider-16px](https://user-images.githubusercontent.com/17748020/33262243-8ece3a26-d35d-11e7-80ee-b845f4155dc8.png)

### 003 @24px
![002-default-slider-24px](https://user-images.githubusercontent.com/17748020/33262244-8ef301d0-d35d-11e7-94b4-2db6f43b1dc0.png)

**Comment by anthonydillon** [comment]
LGTM. @spencerbygraves can you review please.

**Comment by spencerbygraves** [comment]
+1 for 24px

**Comment by kwm14** [comment]
## Visual design

- Approved design @24px

![002-default-slider-24px](https://user-images.githubusercontent.com/17748020/33262244-8ef301d0-d35d-11e7-94b4-2db6f43b1dc0.png)
