### ISSUE TITLE
Is the typography page named correctly/in the right section in docs?

### ISSUE THREAD

**Issue by spencerbygraves** [ubuntudesign/vanilla-design#140]
It took me a while to find our page on [typography](https://docs.vanillaframework.io/en/base/typography). I'm not sure that Headings is the right title for this page (the url is /typography), or that it's in the right section.

The first section I looked in was Global layout, then Text. It's in Page structure.

**Comment by kwm14** [comment]
@spencerbygraves thanks for raising. This will be resolved in this [issue](https://github.com/vanilla-framework/vanilla-framework/issues/1482). Thanks
