### ISSUE TITLE
Design header search box component - Default

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#147]
Original design issue can be found here: https://github.com/ubuntudesign/vanilla-design/issues/10

**Comment by kwm14** [comment]
## Review of header search box

- Review search boxes across our sites and applications
- Looking for consistent patterns in use
- Identify which elements work and don't work

### ubuntu.com
![ubuntu](https://user-images.githubusercontent.com/17748020/34562238-5bef18c2-f145-11e7-881a-5923c9410e52.png)

### docs.ubuntu.com/maas
![maas-docs](https://user-images.githubusercontent.com/17748020/34562224-51f42fc4-f145-11e7-9a02-475705755e4d.png)

### jujucharms.com
![juju](https://user-images.githubusercontent.com/17748020/34562169-21dde082-f145-11e7-8af1-8d9b67ede2a8.png)

### docs.ubuntu.com
- updated and signed-off design by Joana
![docs ubuntu com](https://user-images.githubusercontent.com/17748020/34562282-856f6184-f145-11e7-8942-1f9b839b3237.png)

### snapcraft.io/discover
- not a header search box but still uses most recent Vanilla styling
![snapcraft io](https://user-images.githubusercontent.com/17748020/34562312-ad603510-f145-11e7-812a-58712a9741c4.png)

**Comment by kwm14** [comment]
## Search box styling

- Use Form input styles including active/inactive states/placeholder text
- Accessible focus state
- Updated Search icon
- Correct Close icon
- Speaking with @anthonydillon the dropdown search list uses a browser default as we can't style this so will remain, if not it's easily disabled per website/application

**Comment by kwm14** [comment]
## Initial design exploration

- two versions using Joana's original signed off design and alternate version
- consistent design incorporating all current versions
- works on both light and dark backgrounds

### 001
![header-search-001](https://user-images.githubusercontent.com/17748020/34571178-bdaa0804-f165-11e7-929e-9655b39ccec3.png)

### 002
![header-search-002](https://user-images.githubusercontent.com/17748020/34571189-c5290832-f165-11e7-8d35-ca458ba7d030.png)

**Comment by anthonydillon** [comment]
My preference is 002 as it is where I would expect to find the search icon.
Also, the search icon is the button to submit. It allows the button to
remain when typing.

**Comment by spencerbygraves** [comment]
@kwm14 @anthonydillon I'm not sure we need to include the X for large screens. When typing with a keyboard it's easier to use backspace than reach for the mouse and click the X. Also, if I type and then use the down arrow to select from the list, the highlighted text can also be removed with backspace.

For example, the X seems to be used on small screens only by Amazon, Ebay and Google.

In your research above, the only example with search on the left is jujucharms where the X is used to close an overlay.

I think we could keep the search icon on the right and introduce the X to the left of the search icon on small screens.

What do you think?

**Comment by kwm14** [comment]
@spencerbygraves agree that we probably don't need (x) on large screens but we will definitely need it on medium and small screens.

I'm not sure about search and close icon being next to each-other as you need a minimum of 20px padding around our current icon size for tapping the target area. Personally I prefer the search to the left but I will create two versions based on your feedback so we have a visual we can review :slightly_smiling_face:

**Comment by kwm14** [comment]
## Updated designs
- based on feedback from reviews
- large, medium and small screen views
- 003 with icons next to each-other
- 004 with icons opposite

### 003
![header-search-003](https://user-images.githubusercontent.com/17748020/34614012-eb024c5e-f227-11e7-8937-cdd7d4ce4b36.png)

### 004
![header-search-004](https://user-images.githubusercontent.com/17748020/34614014-eb29de7c-f227-11e7-8926-d94bc5b260e9.png)

**Comment by spencerbygraves** [comment]
@kwm14 Thanks. I prefer 003.

**Comment by kwm14** [comment]
## Updated final design
- from further discussion we've agreed to move forward with version 003
- review of design on dark backgrounds below before sign-off
- @spencerbygraves ready for re-review

### 003 backgrounds
![header-search-003a](https://user-images.githubusercontent.com/17748020/34667611-a8557e94-f461-11e7-856e-19808dec3ca2.png)
