### ISSUE TITLE
Design Mailchimp email template

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#15]

**Comment by kwm14** [comment]
Speaking with @spencerbygraves who has designed email templates for Juju and Snapcraft, he has provided me with current email template styling.

### Juju email template
![01 jaas email welcome a](https://user-images.githubusercontent.com/17748020/33374035-4d6efc78-d4fc-11e7-9c29-a09aa0488682.png)

### Snapcraft email template
![snappy receipt](https://user-images.githubusercontent.com/17748020/33374051-61c2ce16-d4fc-11e7-9bf8-7953884c6cfb.png)

**Comment by kwm14** [comment]
Further investigation @anthonydillon has created email templates here: https://canonical-webteam.github.io/unified-email-template/examples/

Looking at the templates we will follow **Product branded** design for Vanilla.

I have created a **Vanilla mailing list** template in MailChimp and will schedule a push to promote our latest release of v1.6.4. This template will then be used for future releases :)
