### ISSUE TITLE
Update navigation design to work on medium screens

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#16]
Refer to: https://github.com/vanilla-framework/vanilla-framework/issues/736#issuecomment-288687136

**Comment by yaili** [comment]
I like the approach that Bootstrap has here, as it's quite simple: http://getbootstrap.com/components/#navbar

> **Overflowing content**
Since Bootstrap doesn't know how much space the content in your navbar needs, you might run into issues with content wrapping into a second row. To resolve this, you can:
a. Reduce the amount or width of navbar items.
b. Hide certain navbar items at certain screen sizes using responsive utility classes.
c. Change the point at which your navbar switches between collapsed and horizontal mode. Customize the @grid-float-breakpoint variable or add your own media query.

I would propose that for Vanilla we do the same rather than engineer a solution that accommodates an infinite number of links. Thoughts? @kwm14 @spencerbygraves @anthonydillon @barrymcgee

**Comment by barrymcgee** [comment]
@yaili I've now hit this with Ubuntu Vanilla migration and the solution which makes the most sense to me is (c) which would allow users to specify the resolution to suit their own project.. Option (a) and (b) force users to make compromises they may not be able to make.

**Comment by yaili** [comment]
Which would be the default setting?

**Comment by barrymcgee** [comment]
768px would seem sensible?

**Comment by yaili** [comment]
OK, sounds good.
