### ISSUE TITLE
Add info as a notification style

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#17]
_From @spencerbygraves on March 30, 2017 10:36_

# Pattern proposal

The docs team have requested an info admonition style and I think it might be a useful addition to Vanilla. It's coincidentally come up in some new juju designs.

![image](https://cloud.githubusercontent.com/assets/9105999/24500439/4ccd56c2-153d-11e7-91d1-95f11b5b2a92.png)

https://docs.vanillaframework.io/en/patterns/notification

_Copied from original issue: vanilla-framework/vanilla-framework#987_

**Comment by yaili** [comment]
_From @anthonydillon on April 24, 2017 13:11_

:+1:

**Comment by anthonydillon** [comment]
I believe this was excepted. This issue should be moved to
Vanilla-framework for implemention.

**Comment by yaili** [comment]
Yes, I need to add to specs.

**Comment by yaili** [comment]
Added to specs.
