### ISSUE TITLE
Update background color of Neutral button

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#171]
Recently me and @spencerbygraves have noticed that the current _hover-state_ on our Neutral button isn't working on _p-strip--light_ backgrounds.

We will investigate and propose a new hover state color to solve this issue:
- test on various coloured backgrounds
- make sure it's AA/AAA accessible

**Comment by kwm14** [comment]
@spencerbygraves proposal - https://codepen.io/spencerbygraves/pen/XZmdMa

**Comment by kwm14** [comment]
## First exploration of new hover state proposals

### 001
- @spencerbygraves proposal to use our mid-light color `#CDCDCD `
- WCAG AAA accessible on both Normal and Large text
![mid-light-neutral-button](https://user-images.githubusercontent.com/17748020/39761005-cfff0fac-52ce-11e8-9b97-e5b94e0b6e02.png)

### 002
- proposal to use our current light color `#F7F7F7 ` but have 10% `#000000` on hover, similar to how we apply hover-state to all our other button states
- new hover color `#DDDDDD`
- WCAG AAA accessible on both Normal and Large text
![10 -darker-neutral-button](https://user-images.githubusercontent.com/17748020/39761393-e15c559c-52cf-11e8-8e2d-bee9bff4c72b.png)

### 003
- proposal to use our mid-dark color `#666666 ` probably to dark and the switch of white/black text isn't ideal
- WCAG AAA accessible on both Normal and Large text using `#FFFFFF` foreground color only
![mid-dark-neutral-button](https://user-images.githubusercontent.com/17748020/39761518-38e06cfe-52d0-11e8-91a7-94f6bd9fcad7.png)

@spencerbygraves ready for design review 😄

**Comment by spencerbygraves** [comment]
@kwm14 I'm happy to go with 002, if it means the hover states are the same on all buttons.

**Comment by kwm14** [comment]
Design signed-off, I've created an dev issue to update in next iteration small tasks [here](https://github.com/vanilla-framework/vanilla-framework/issues/1802) 👍
