### ISSUE TITLE
Update navigation styles according to findings

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#208]
Discussed notes can be found here: https://github.com/ubuntudesign/vanilla-design/issues/207

**Comment by kwm14** [comment]
## Navigation font size

Looking at the examples I showed in _**Design review**_ earlier today they use these values:
- Apple - `14px`
- Google Store - `14px`
- Docker - `14px`
- Microsoft - `15px`
- Intel - `16px`
- Joyent - `16px`

@spencerbygraves @lyubomir-popov currently in Vanilla navigation items are font-size: `14px`, I know we've recently discussed moving up to `16px`. Is this still the case?

**Comment by spencerbygraves** [comment]
@kwm14 Let's see how it looks when you try the design without dividers etc. Thanks.

**Comment by lyubomir-popov** [comment]
@spencerbygraves @kwm14 I'm personally a fan of having as few font-sizes on a page as possible. 

A couple of examples to illustrate why - 

• An excerpt from Massimo Vignelli's canon:

<img width="1135" alt="screen shot 2018-03-20 at 12 15 21" src="https://user-images.githubusercontent.com/2741678/37653966-7afda750-2c38-11e8-9d53-63319c6e7833.png">

• An example of this concept applied to the web, in google's parent company alphabet. no menu here, just the harmony of having only 2 font sizes on the page.

[https://abc.xyz/investor/](https://abc.xyz/investor/)

<img width="1306" alt="screen shot 2018-03-20 at 12 18 33" src="https://user-images.githubusercontent.com/2741678/37654076-dcc4a7cc-2c38-11e8-9b84-44a8ea485370.png">

• And an example where the menu and tabstrip match everything else at 16px.

![image](https://user-images.githubusercontent.com/2741678/37654430-f03a989c-2c39-11e8-91ab-7ab6a9349651.png)

Not suggesting these as a hard rule, of course if there's no space to fit things at 16, then 14 becomes a necessity. But I also don't see why a menu would be smaller than body copy, if it wasn't for lack of space.

**Comment by kwm14** [comment]
## Color accessibility discussion
Looking at color values for a hover/selected state which can work on both light and dark backgrounds, we found that these values worked best. 
![image](https://user-images.githubusercontent.com/17748020/37667261-7c5ce310-2c59-11e8-9223-5fb13e7cb613.png)
Next steps is to experiment these values across our Marketing and Cloud websites.

**Comment by kwm14** [comment]
## Navigation first steps
Identifying existing/new font size and paddings.

### 14px/16px
![16px](https://user-images.githubusercontent.com/17748020/37669251-4e4faf70-2c5e-11e8-86c8-7b32ee0a0722.png)

### 14px/24px
![24px](https://user-images.githubusercontent.com/17748020/37669252-4e7398cc-2c5e-11e8-94ae-a459bbb87814.png)

### 16px/16px
![16px](https://user-images.githubusercontent.com/17748020/37669368-877d838a-2c5e-11e8-9e46-74ddd419b738.png)

### 16px/24px
![24px](https://user-images.githubusercontent.com/17748020/37669381-94bbff90-2c5e-11e8-80f8-2c0c73facd97.png)

**Comment by kwm14** [comment]
## Design review
- 16px preferred font-size
- keep to the baseline of 16px so increase padding x2

**Comment by kwm14** [comment]
## Updated default navigation
- taking feedback into consideration
- created light and dark version
- next steps to apply these style to our Marketing and Cloud websites

### Light version
![32px](https://user-images.githubusercontent.com/17748020/37703856-f70cf57e-2cee-11e8-8aba-113e169ffe83.png)

### Dark version
![32px](https://user-images.githubusercontent.com/17748020/37703865-ff87bc34-2cee-11e8-9cd2-e392698829fb.png)

**Comment by kwm14** [comment]
## Ubuntu orange not accessible
Looking at a few other marketing sites that use Ubuntu orange as there background color we've found that neither dark or light values are accessible.
- https://design.ubuntu.com/
- https://linuxcontainers.org/
- https://developer.ubuntu.com/
- http://cn.ubuntu.com/
- https://jp.ubuntu.com/

Quick win would be to update these sites to use our default light background, but speaking we @spencerbygraves we should ideally make it work with our brand color.

**Comment by kwm14** [comment]
## Testing sites reverting to default light navigation
If we were unable to solve the accessible issue with Ubuntu orange without changing the hex value, below shows examples of sites currently using our default light background.

### design.ubuntu.com
![32px](https://user-images.githubusercontent.com/17748020/37720195-aa0572b2-2d1e-11e8-9bfe-a4d047235e24.png)

### linuscontainers.org
![32px](https://user-images.githubusercontent.com/17748020/37720201-afe8c27e-2d1e-11e8-8374-eb94b7f11be7.png)

### developer.ubuntu.com
![32px](https://user-images.githubusercontent.com/17748020/37720227-c1e7bc46-2d1e-11e8-9f10-b214a3361d17.png)

### cn.ubuntu.com
![32px](https://user-images.githubusercontent.com/17748020/37720237-c7b49fa4-2d1e-11e8-84b5-5072921ab709.png)

**Comment by kwm14** [comment]
## Mobile navigation
- Explorations for mobile version of navigation
- @spencerbygraves ready for review

### 001 - Inheriting styling from proposed desktop navigation
![001-mobile-light-navigation](https://user-images.githubusercontent.com/17748020/37822693-152337e4-2e7f-11e8-8469-04591a6ca91e.png)

### 002 - Dividing lines 8px content height
![002-mobile-light-navigation](https://user-images.githubusercontent.com/17748020/37822792-6996d344-2e7f-11e8-8efc-bb14a0763c10.png)

### 003 - Dividing lines 16px viewport height
![003-mobile-light-navigation](https://user-images.githubusercontent.com/17748020/37822826-90174e5e-2e7f-11e8-9a50-25e3ce5db529.png)

**Comment by spencerbygraves** [comment]
@kwm14 thanks for all these investigations, looking good.

As there's a lot here, I suggest we use the next design meeting to make some decisions. I'll add it to the agenda.

**Comment by kwm14** [comment]
@spencerbygraves perfect, sounds good to me 👍

**Comment by kwm14** [comment]
## Design review
- Meetings notes can be found here: https://github.com/ubuntudesign/meeting-notes/issues/253
- Next steps review with @pmahnke and @carlaberkers before creating a design spec

**Comment by kwm14** [comment]
## Next steps
- @Caleb-Ellis to create a couple of demos we can review
- I will create an issue listing out design styles for each one 
- book a meeting to review demos with @spencerbygraves @pmahnke @carlaberkers

**Comment by kwm14** [comment]
- Issue to build demos raised here: https://github.com/vanilla-framework/vanilla-framework/issues/1652
