### ISSUE TITLE
Document icons that are already being used across sites

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#21]
[Notes from Vanilla brochure theme workshop](https://github.com/ubuntudesign/meeting-notes/issues/155):
- Needs design work
  - Need to go through all sites and see which icons are being used where - Matthieu did some work on this already
- It would be good to have one place where all icons live - have a Vanilla set, starting with icons that we're already using

**Comment by yaili** [comment]
- Accordion expand
- Accordion collapse
- List tree expand
- List tree collapse
- List tree expand
- Loading (spinner)
- Chevron 
- Close
- Help
- Information
- Delete
- Error
- Warning
- External link
- Contextual menu
- Menu
- Code snippet
- Search
- Tick
- Success
- Copy to clipboard

**Comment by spencerbygraves** [comment]
Designs and specs have been added to code in the Icons folder.
