### ISSUE TITLE
Design product docs homepage template

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#217]
## Docs content review 
Looking at documentation copy for products I wanted to identify sections that are consistent, so I can then identify components/patterns to use.

![img_1008](https://user-images.githubusercontent.com/17748020/38670644-41fd6f56-3e41-11e8-9c92-c716469345a6.jpg)

**Comment by kwm14** [comment]
## 'Getting started' section
- I explored a few variations but looking at the copy [here](https://docs.google.com/document/d/1AH9z7jUPiNYHQj-6eDdBOgc7tYqD58jjsboIQQ55Ac8/edit#) I think the stepped list is best suited, sitting alongside an image to give the homepage a better visual cue

### Template example
![getting-started-003](https://user-images.githubusercontent.com/17748020/38728075-b9d7b624-3f06-11e8-9444-aa3373d5c738.png)

## 'What's new' section
- As all of these are articles/webinars so it was best to follow current patterns seen on ubuntu.com

### Template example
![what s-new-003](https://user-images.githubusercontent.com/17748020/38728239-395d9d64-3f07-11e8-873e-8467a2b19635.png)

## 'Geting support' section
- I explored this section the most from a matrix layout to inline links and eventually came to the solution of an icon list

### Template example
![getting-support-007](https://user-images.githubusercontent.com/17748020/38728308-74bcaa3a-3f07-11e8-973e-4cf29552ac97.png)

## 'Contribute' section
- Most of this content is external linking to community, blogs or IRC channles so thought it was best to keep it simple with a clean divider list

### Template example
![contribute-section-004](https://user-images.githubusercontent.com/17748020/38728434-c9fb413c-3f07-11e8-9391-143dd61f2eae.png)

**Comment by kwm14** [comment]
### 001 - Document homepage example
- First attempt at combining all sections into one template

![documentation-home-template-002](https://user-images.githubusercontent.com/17748020/38731007-a9ef5be0-3f10-11e8-887f-fb1d7d93b078.png)

**Comment by anthonydillon** [comment]
Looks awesome!

**Comment by kwm14** [comment]
## Design review
- looking good so far just a few updates
- look at hierarchy of type
  - hero section update to h2
  - getting started update to h3
  - what's new remover muted heading and update to use h3
- add this style to one of our product sites so we can see what it looks like with real content

**Comment by kwm14** [comment]
### 002 - Document homepage example
- Taking all feedback from Design review into consideration
- Applied correct grid layout
- @spencerbygraves ready for re-review

![documentation-home-template-003](https://user-images.githubusercontent.com/17748020/38859550-2e3632f8-4226-11e8-915e-cc4ab8d46302.png)

**Comment by spencerbygraves** [comment]
Thanks @kwm14, not sure about the horizontal lines, with the right spacing we may not need them. Also, I'd probably make the Suru background less prominent, and perhaps find an image to use from the product, or was that your intention in the Get Started section?

**Comment by kwm14** [comment]
@spencerbygraves thanks for your feedback, just to clarify:
- try it without dividing lines between sections?
- the Suru background in the hero is too illustrate the background it will inherit dependant on the marketing site it's attached too
- regarding the 'Get started' section that is my intention, when I upload the product sites you will see what I'm trying to achieve

**Comment by spencerbygraves** [comment]
@kwm14 ok, great. Just try without the lines then. Thanks.

**Comment by kwm14** [comment]
Template signed-off. I will now apply content from Product sites:
- conjure-up
- MAAS
- Juju
- Enterprise Proxy

**Comment by kwm14** [comment]
### 004 - Document homepage example

- Updated template design based on revisions [here](https://github.com/ubuntudesign/vanilla-design/issues/220) to Juju.

![documentation-home-template-005](https://user-images.githubusercontent.com/17748020/39259309-069e3c0c-48ae-11e8-9bf3-53378f5017a2.png)

**Comment by anthonydillon** [comment]
@kwm14 Created an example of the latest design using Vanilla and CSS Grid https://codepen.io/anthonydillon/full/qYZQoV/

**Comment by kwm14** [comment]
@anthonydillon that looks wicked! 🥇
