### ISSUE TITLE
Create docs homepage template for MAAS

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#219]
Update content using layout patterns defined on homepage template [here](https://github.com/ubuntudesign/vanilla-design/issues/217).

**Comment by anthonydillon** [comment]
Do you mean in Sketch? There is already a template for MAAS.
https://vanilla-framework.github.io/vanilla-framework/examples/templates/maas-layout/

**Comment by kwm14** [comment]
@anthonydillon no it's for Documentation homepage 👍 I'll update issue title 😄

**Comment by kwm14** [comment]
### 001 - MAAS documentation homepage
- First attempt adding MAAS content to Documentation template
- Retaining navigation from marketing website
- Ready for review @spencerbygraves 

![maas-documentation-home-template-002](https://user-images.githubusercontent.com/17748020/38939181-3caeb8a6-431f-11e8-880d-b006b85ce2d1.png)

**Comment by kwm14** [comment]
## Design review
_with @spencerbygraves_ 

- removed stepped list (numbers)
- span content full width of page: -col. 3-col and 4-col dependent on content in section

**Comment by kwm14** [comment]
### 001 - MAAS documentation homepage
- Taking all feedback into consideration
- With dividing lines added back in
- @spencerbygraves ready for re-review

![maas-documentation-home-template-003](https://user-images.githubusercontent.com/17748020/39058265-3fde560e-44b3-11e8-9934-0ca40ae065c2.png)

**Comment by kwm14** [comment]
### 003 - MAAS documentation homepage
- Updated based on further iterations to Juju and generic template
- @spencerbygraves ready for re-review 😄

**Comment by kwm14** [comment]
@evilnick @pmahnke please find above the latest solution for a homepage template **003** for MAAS.
- @spencerbygraves has given Design+1 but I wanted you to check copy written in Budapest 😄
- if you wanted to edit copy please feel free and I can then update the design   
- MAAS copy: https://docs.google.com/document/d/1AH9z7jUPiNYHQj-6eDdBOgc7tYqD58jjsboIQQ55Ac8/edit#heading=h.k4heplfwhf2b

**Comment by kwm14** [comment]
Template agreed. Will include issue in build for reference.
