### ISSUE TITLE
Spec slider pattern

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#22]
[Notes from Vanilla brochure theme workshop](https://github.com/ubuntudesign/meeting-notes/issues/155):
- Agreed name: **slider** (`p-slider`)
- Verify if Jaas slider is the correct/final version
- Should be in Vanilla: ubuntu.com has slider (contribute), Landscape and Jaas too

@spencerbygraves could you confirm what is the latest version of the Jaas sliders?

**Comment by spencerbygraves** [comment]
We have this in Juju, but I don't think we actually use it anywhere at the moment:

![image](https://user-images.githubusercontent.com/9105999/27827582-dc325f3e-60af-11e7-8d68-2afa5c946e86.png)

And I believe this was the latest from the platform team:

![image](https://user-images.githubusercontent.com/9105999/27827642-297575ba-60b0-11e7-8b83-986aab01f508.png)

MAAS doesn't have a slider pattern at the moment.

#335280 is the agreed colour for info/awareness, not green.

**Comment by spencerbygraves** [comment]
I've updated the Juju version with the correct blue:

![image](https://user-images.githubusercontent.com/9105999/27828350-afbdbf26-60b3-11e7-8ea3-13f98dbc8247.png)

**Comment by kwm14** [comment]
We also use the slider component on ubuntu.com for contirbutions [here](https://www.ubuntu.com/download/desktop/contribute?version=16.04.3&architecture=amd64), so it's valid to create a design spec and add to Vanilla as it's been used in more than 2 places..

**Comment by kwm14** [comment]
Closing issue and this work item has been scheduled this iteration, to follow it's track you can find it [here](https://github.com/ubuntudesign/vanilla-design/issues/126).
