### ISSUE TITLE
Create docs homepage template for Vanilla

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#222]
Create a template based on work done [here](https://github.com/ubuntudesign/vanilla-design/issues/217) for Documentation.

**Comment by kwm14** [comment]
### 001 - Vanilla documentation homepage
- First attempt adding Vanilla content to Documentation template
- Installation content is long and maybe this layout doesn't work so well?
- Ready for review @spencerbygraves 

![vanilla-docs-home-template-001](https://user-images.githubusercontent.com/17748020/39518229-3a1d031e-4dfa-11e8-9515-a3590251fba1.png)

**Comment by spencerbygraves** [comment]
@kwm14 I don't think this layout works for content pages. I thought it would be for the homepage only and content pages would be similar to what we have now.

Are we keeping the version and contents on the right as we have now?

**Comment by kwm14** [comment]
@spencerbygraves this isn't the contents pages it's for the homepage content only seen on docs.vanillaframework.io :smile:

**Comment by kwm14** [comment]
## Design review
_with @spencerbygraves_ 

- some dividing lines would help it read better
- perhaps Install via npm could be numbered 1 & 2, as the others are alternative
- speak with @anthonydillon whether we can remove _'Using with Github Pages via Git submodules'_ from installation guide as most users either **npm** or **hotlink**...

**Comment by kwm14** [comment]
### 003 - Vanilla documentation homepage
- updated design taking feedback into consideration 
- adding dividing lines between 'Getting started' installation instructions
- 8-col vs 6-col layout (bit jarring)

![vanilla-docs-home-template-004](https://user-images.githubusercontent.com/17748020/39572793-8425b95a-4ec8-11e8-8c78-604362210025.png)

### 004 - Vanilla documentation homepage
- updated layout to use 6-col vs 6-col so we have a strong key-line down the page to separate content
- content to the left tight to margin so will do an alternate version with `prefix-1` to allow for more space between both columns with out losing the key-line
![vanilla-docs-home-template-005](https://user-images.githubusercontent.com/17748020/39572802-8bd25e2e-4ec8-11e8-91f2-260c1ed97621.png)

**Comment by kwm14** [comment]
### 005 - Vanilla documentation homepage
- updates added based on reviews to above designs

![vanilla-docs-home-template-006](https://user-images.githubusercontent.com/17748020/39573549-8ea8dd6e-4ecb-11e8-92a6-6e1b3598354c.png)

**Comment by kwm14** [comment]
Build issue created [here](https://github.com/vanilla-framework/vanilla-framework/issues/1798) and added to Template build epic with other product templates 👍
