### ISSUE TITLE
Investigate and decide new icon size set

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#224]

**Comment by kwm14** [comment]
## Review of all components and icon sizes
![img_1074](https://user-images.githubusercontent.com/17748020/39879464-c84a51a4-5472-11e8-906b-cd5d4f0ede0f.JPG)

**Comment by spencerbygraves** [comment]
@kwm14 This looks fine, apart from the media object updates. Might those sizes be too small, for an image associated with an event for example?

In comparison, 3rem seems ok for the matrix where it's likely to be an icon or logo.

**Comment by kwm14** [comment]
@spencerbygraves ok cool thanks. 

Looking back at them now the values do look small, did a quick mockup to see the proposed updated sizes and they do look too small.

![media-object-large](https://user-images.githubusercontent.com/17748020/39922954-99298d8e-5519-11e8-89d5-84ab6f59216d.png)
![media-object-small](https://user-images.githubusercontent.com/17748020/39922955-994d9b20-5519-11e8-811b-cb751d22af03.png)

Seeing as the Matrix component uses `3rem` as an icon size maybe we can apply the same size for the media object so they're consistent?

In terms of media object large is this used for charm and snap details pages?

**Comment by lyubomir-popov** [comment]
@kwm14 @spencerbygraves this may turn out a lot more complex than I originally thought when I raised the issue, apologies. Maybe we should think of contexts (as in what is it sitting next to), identify how many contexts we currently have, does it match a heading's height, or a heading plus first line, etc., and see where we can standardise usages.

Also not convinced line-height is the best thing to match - as the letters cover about .6 of the line-height, so maybe slightly smaller would be better. Easiest to tell if we just put them all on one page and make a decision.

Some random thoughts:

On one hand, would be good to "snap" values that are roughly same to the same value. So if 1.5, 2, 2.5 maybe we can omit one of the three and snap the outliers to one of the other sizes.

On the other hand, many of the sizes are matching what sits next to the icon - a single heading, or a group of H1 + p, or h4 + p, etc., where the icon visually matches the height of the heading + first one or two lines of the copy.

Also I just noticed someone has added a reduction to the matrix images in the beta nav css (reduced to 2rem) (I assume it was requested, possibly by Mark)
<img width="1068" alt="screen shot 2018-05-11 at 13 10 34" src="https://user-images.githubusercontent.com/2741678/39923715-bbcf37f0-551c-11e8-9db2-685a7ccaab48.png">


Too many moving parts :) and can be frustrating I know, maybe we can run through the scenarios in one of the design meetings.

**Comment by spencerbygraves** [comment]
@kwm14 @lyubomir-popov Yes, I think it would be good to reduce the number of sizes if we can. We should discuss choosing image sizes suitable for the likely content and balancing it visually, vs always matching line heights.

**Comment by kwm14** [comment]
@spencerbygraves @lyubomir-popov agree with both of you, let's revisit this on Monday in the design review and we can discuss and conquer as a team 👍 

Looked up heading sizes associated to the components so we have values to work from:

### Heading line heights
- Heading icon (small) - `2rem` 
- Heading icon (large) - `2.5rem`
- Media object - `2rem`
- Media object(large) - `3.5rem`

**Comment by kwm14** [comment]
## Design review
Meeting notes can be found [here](https://github.com/ubuntudesign/meeting-notes/issues/270), but high level actions for this task is for:
- myself and @lyubomir-popov to look at Vanilla icon sizes in context, including media object.
  - Maybe go for stacked if it works better.

**Comment by kwm14** [comment]
## Updated proposal
- Taking feedback from design review
- Use current 16/24/32/48/96px value set for icons

### Icon size updates
- Media object (large) - `6rem` no update
- Media object - `5rem` update to `3rem`
- Heading icon (large/medium screens) - `3.75rem` update to `3rem`
- Heading icon (small screens) - `2.5rem` update to `2rem`
- Social icons - `2.5rem` update to `2rem`

![96](https://user-images.githubusercontent.com/17748020/40126648-acedbc54-5925-11e8-9984-c15a7eacb40f.png)

@lyubomir-popov can you apply these sizes to your one-page demo. Then we can review with @spencerbygraves 👍

**Comment by kwm14** [comment]
@Caleb-Ellis can you create me a demo showing current icon sizes vs newly proposed listed below in one PR:

### Icon size updates
Media object (large) - `6rem` no update
Media object - `5rem` update to `3rem`
Heading icon (large/medium screens) - `3.75rem` update to `3rem`
Heading icon (small screens) - `2.5rem` update to `2rem`
Social icons - `2.5rem` update to `2rem`

Thanks 👍

**Comment by kwm14** [comment]
LGTM 👍 

One question, do we need _Heading icon / Small_ as an example? Currently _Heading icon / Default_ scales from large to small screen...
