### ISSUE TITLE
Define behaviour of search pattern

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#23]
[Notes from Vanilla brochure theme workshop](https://github.com/ubuntudesign/meeting-notes/issues/155):
- Agreed name: **search** (`p-search`)
- Needs design work:
  - Define behaviour, search icon and x icon placement, placeholder text and colour
  - Do we need to integrate auto-complete/live results?
  - Consider large variation (e.g. when used in the content area of a page of search results)
  - Consider how it works on different background colours (light, dark, …)

**Comment by kwm14** [comment]
This issue is linked with this [issue](https://github.com/ubuntudesign/vanilla-design/issues/10).
