### ISSUE TITLE
Design sub navigation within the navigation component

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#243]
_Original comment from @anthonydillon_ 

> I number of times now we have had to implement a drop-down navigation locally which should be added to Vanilla.

**Comment by kwm14** [comment]
## Examples of sub navigations

### Salesforce
![salesforce](https://user-images.githubusercontent.com/17748020/47021461-6f06af80-d153-11e8-9c53-f652048b5857.png)

### Mailchimp
![mailchimp](https://user-images.githubusercontent.com/17748020/47021482-76c65400-d153-11e8-81e8-2fd379b358ef.png)

### Heroku
![heroku](https://user-images.githubusercontent.com/17748020/47021507-7f1e8f00-d153-11e8-8d3e-0d875b5d3471.png)

### Bulma
![bulma](https://user-images.githubusercontent.com/17748020/47021522-85ad0680-d153-11e8-9b59-402d819a918b.png)

**Comment by kwm14** [comment]
## Cloud application examples
Implemented in Snappy and Landscape.

### Snappy
- Right aligned
- Font-size: `1rem`
- Padding: `1rem` left/right, `0.5rem` top/bottom

![screenshot 2018-10-16 at 15 57 36](https://user-images.githubusercontent.com/17748020/47026306-10463380-d15d-11e8-962f-3d966209f3db.png)

### Landscape
- Left aligned
- Font-size: `0.875rem`
- Padding: `1rem` left/right/top/bottom

![screenshot 2018-10-16 at 16 02 43](https://user-images.githubusercontent.com/17748020/47026327-1b00c880-d15d-11e8-9c9b-b5c57af58a1f.png)

**Comment by kwm14** [comment]
## First exploration
Taking influence from our existing styles implemented and using Vanilla style components.

### 001
- Left-aligned menu
- Inherit navigation menu item styling (padding: `1rem` left/right, `.75rem` top/bottom)
- Inherit `p-button--neutral` hover state
- Inherit `p-card` dropdown styling (border-radius: `2px` applied to bottom corners only)
- Dividing lines

![sub-navigation-001](https://user-images.githubusercontent.com/17748020/47028385-3a015980-d161-11e8-8db3-55be5f15bec8.png)

### 002
- Same styling as 001 design but...
- Center-aligned menu
- Inherit `p-card--highlighted` dropdown styling

![sub-navigation-002](https://user-images.githubusercontent.com/17748020/47028693-c6ac1780-d161-11e8-89b6-b2a0923abe70.png)

### 003
- Left-aligned menu
- Inherit `p-button` styling (padding: `1rem` left/right, `6px` top/bottom)
- Inherit `p-button--neutral` hover state
- Inherit `p-card--highlighted` dropdown styling (border-radius: `2px` applied to bottom corners only with solid border)
- No dividing lines

![sub-navigation-003](https://user-images.githubusercontent.com/17748020/47028900-391cf780-d162-11e8-8266-4999d66d2c9a.png)

### 004
- Same styling as 003 design but...
- Inherit `p-card--highlighted` dropdown styling (positioned `4px` below navigation as per our `.p-contextual-menu` interaction)

![sub-navigation-004](https://user-images.githubusercontent.com/17748020/47029079-931dbd00-d162-11e8-901b-5b05f49ad0ce.png)

@spencerbygraves ready for first review 😉

**Comment by kwm14** [comment]
## Updated design
- Taking feedback from Design and UX conversations
- Decided to use chevrons as a sub-nav indicator due to it being used across ubuntu.com and a couple of our cloud applications
- @spencerbygraves @clagom ready for another review 👍 

### 005
### Nav hover state
![sub-navigation-006](https://user-images.githubusercontent.com/17748020/47214033-a0ba8900-d394-11e8-934e-53f53055c392.png)

### Nav selected state
![sub-navigation-006b](https://user-images.githubusercontent.com/17748020/47214034-a0ba8900-d394-11e8-9a3d-07734c8751fa.png)

### Sub-nav hover state
![sub-navigation-006c](https://user-images.githubusercontent.com/17748020/47214035-a0ba8900-d394-11e8-807f-030f79db4dbf.png)

**Comment by kwm14** [comment]
## Design review
_with @spencerbygraves_ 
- I'm not sure we need a colour for selected, maybe the chevron changing direction would be enough
- Also, if this is on hover, would we even have a selected state?

**Comment by clagom** [comment]
I think in we would need a a clearer active state for the open selection, when you have top navigation items near to each other is not clear which one is open (we had a similar case in MAAS). The chevron is an indication, but may not be enough. Even just a subtle change on the background would help.

Example with mouse hover:
https://www.w3schools.com/css/css_dropdowns.asp

Example with click to open:
https://www.w3schools.com/howto/howto_css_dropdown_navbar.asp

**Comment by clagom** [comment]
The example from Heroku or Bulma are good ones I think.

**Comment by kwm14** [comment]
Thanks @clagom would reverting back to design 005 suffice? @spencerbygraves wasn't sure whether we needed a state to indicate selection as the chevron animation was enough...

**Comment by clagom** [comment]
I think 005 is clearer, are we going with click or mouse hover?

**Comment by kwm14** [comment]
@clagom ok great. I was going to propose click as this is the interaction on Snappy, Landscape and the new global sub menu on ubuntu.com

**Comment by kwm14** [comment]
## Revert design
After further discussion 005 seems the best solution to move forward with.

### 005
### Nav hover state
![sub-navigation-006](https://user-images.githubusercontent.com/17748020/47214033-a0ba8900-d394-11e8-934e-53f53055c392.png)

### Nav selected state
![sub-navigation-006b](https://user-images.githubusercontent.com/17748020/47214034-a0ba8900-d394-11e8-9a3d-07734c8751fa.png)

### Sub-nav hover state
![sub-navigation-006c](https://user-images.githubusercontent.com/17748020/47214035-a0ba8900-d394-11e8-807f-030f79db4dbf.png)

**Comment by kwm14** [comment]
## Applied design to Cloud applications
- Applied reverted design style to Snapcraft, Juju, MAAS and Landscape 
- @spencerbygraves let me know what you think 👍 

### Snapcraft
![sub-navigation-snapcraft-hover](https://user-images.githubusercontent.com/17748020/47294607-85a28000-d605-11e8-8074-e8f3fa2dcaac.png)
![sub-navigation-snapcraft-selected](https://user-images.githubusercontent.com/17748020/47294608-85a28000-d605-11e8-808c-4fef37ad36de.png)
![sub-navigation-snapcraft-sub-hover](https://user-images.githubusercontent.com/17748020/47294609-85a28000-d605-11e8-933e-b908dd11b6ff.png)

### Juju
![sub-navigation-juju-hover](https://user-images.githubusercontent.com/17748020/47294624-905d1500-d605-11e8-9a84-acee5b2f95bd.png)
![sub-navigation-juju-selected](https://user-images.githubusercontent.com/17748020/47294625-905d1500-d605-11e8-8f2a-65059bd652cf.png)
![sub-navigation-juju-sub-hover](https://user-images.githubusercontent.com/17748020/47294626-905d1500-d605-11e8-8049-0d6f80e52075.png)

### MAAS
![sub-navigation-maas-hover](https://user-images.githubusercontent.com/17748020/47294657-a10d8b00-d605-11e8-94ca-1809281517d8.png)
![sub-navigation-maas-selected](https://user-images.githubusercontent.com/17748020/47294658-a1a62180-d605-11e8-9ec6-a4dfc38ba25b.png)
![sub-navigation-maas-sub-hover](https://user-images.githubusercontent.com/17748020/47294659-a1a62180-d605-11e8-9025-4c4863e3f8fe.png)

### Landscape
![sub-navigation-landscape-hover](https://user-images.githubusercontent.com/17748020/47294670-a9fe5c80-d605-11e8-9703-bc90a380aaf6.png)
![sub-navigation-landscape-selected](https://user-images.githubusercontent.com/17748020/47294671-a9fe5c80-d605-11e8-8e5e-52136b618bf1.png)
![sub-navigation-landscape-sub-hover](https://user-images.githubusercontent.com/17748020/47294672-a9fe5c80-d605-11e8-8b62-98b6eaa9f41a.png)

**Comment by kwm14** [comment]
Will create a issue for build 💯
