### ISSUE TITLE
Context menu icon looks like a drag handle

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#244]
_Original comment by @matthewpaulthomas_ 

> [The Vanilla icons](https://docs.vanillaframework.io/en/patterns/icons) include a “contextual menu” icon, `p-icon--contextual-menu`:

> ![context-menu-icon](https://user-images.githubusercontent.com/19801137/39998147-1d1f221a-577d-11e8-85ef-0566d1b804ad.png)

> In the January snapcraft.io prototype, @lyubomir-popov used this icon for a menu inside a card:

> ![release cards](https://user-images.githubusercontent.com/19801137/39998313-9d93117c-577d-11e8-89ed-17d24daf09c2.png)

> Unfortunately, test participants misinterpreted the icon as a drag handle:
> - “Because you have this little design element right here, the three lines, I just kind of assumed that you can just drag this and drop, you know?”
> - “I think immediately I’d try dragging the little dots.”

> Some people, through repeated exposure, may recognise this icon as a menubutton in the context of a header bar in an Android or Google app. But it may not be suitable for Vanilla sites in general.

**Comment by spencerbygraves** [comment]
@kwm14 I used the icon below in a recent design for Machine view in Juju. This hasn't been built, and may not be the correct solution but I thought I should share it.

![image](https://user-images.githubusercontent.com/9105999/40352956-277de2c4-5da8-11e8-891e-8671a7931a4b.png)

**Comment by lyubomir-popov** [comment]
@spencerbygraves @kwm14 I think the main source of confusion is the rectangle shapes - as that is midway between a kebap icon[ (circles / squares) ](https://thenounproject.com/term/kebab-menu/198755/) and drag handle (thin horizontal lines ).

I like the circles in the above example, but do they need to be horizontal seems like it will require more (white) space, and is there a good reason to depart from the widely used vertical style (as in chrome's address bar in the upper right corner)?

**Comment by spencerbygraves** [comment]
@kwm14 @lyubomir-popov I'm not against them being vertical.

**Comment by matthewpaulthomas** [comment]
> as in chrome's address bar in the upper right corner

That’s a popular example of what I was referring to as “a menubutton in the context of a header bar in an Android or Google app”. But some Chrome users will understand the kebab icon partly because it used to be a hamburger icon, and maybe even because it was a spanner icon before that. But no Vanilla uses will have that history.

I could be wrong, but it seems like Google apps give the kebab icon a helping hand in recognisability by putting it at the end of something:

- the end of a set of buttons, as in Google Docs
  ![kebab in google drive](https://user-images.githubusercontent.com/19801137/40376508-6b554378-5de6-11e8-8bab-852cd8f857fa.png)

- the end of a narrow bar, like a phone app’s header
  ![kebab icon android](https://user-images.githubusercontent.com/19801137/40376609-a54f9308-5de6-11e8-8982-1fd6efc5c559.png)

- the end of a list item.
  ![kebab menu in a list](https://user-images.githubusercontent.com/19801137/40376794-328eb47e-5de7-11e8-8323-31c0fd2e9887.png)

In the snapcraft.io and Juju cases above, that isn’t possible. So we might need something more obvious.

**Comment by kwm14** [comment]
Thanks all for your comments. @matthewpaulthomas in terms of the snapcraft.io prototype example, has this design been implemented?

I've had a browse of the market and these are the examples I've found:

### Carbon
- They use a similar styling to @matthewpaulthomas example of Google above

![carbon-menu](https://user-images.githubusercontent.com/17748020/42890059-cf1be940-8aa3-11e8-89ae-689ccb7536e6.png)

### Ant Design, GitHub and Trello
- They all use a horizontal kebab menu similar to @spencerbygraves Juju concept 
- Give or take differences in dot weight
![antdesign-menu](https://user-images.githubusercontent.com/17748020/42890126-f81c857a-8aa3-11e8-86b4-72f58b832fcc.png)

![github-menu](https://user-images.githubusercontent.com/17748020/42890139-ff18642a-8aa3-11e8-970c-8b818a686f2a.png)

![nachos-trello-menu](https://user-images.githubusercontent.com/17748020/42890151-029cc01e-8aa4-11e8-9b3b-2e4087934246.png)

### Salesforce
- They use a different approach with an icon inside a button....food for thought?
![salesforce-menu](https://user-images.githubusercontent.com/17748020/42890251-44318ce4-8aa4-11e8-8abb-62f049b98039.png)

**Comment by kwm14** [comment]
### First iteration
- Using Juju's use-case as an example of the context-menu icon in situ
- Followed `2px` weight styling for icons
- Followed `16px` size for icons
- @spencerbygraves ready for design review

**001**
![juju-example-001](https://user-images.githubusercontent.com/17748020/42946387-a3ea0300-8b62-11e8-9251-04f459e82816.png)

**002**
![juju-example-002](https://user-images.githubusercontent.com/17748020/42946389-a4189a1c-8b62-11e8-8600-551b80d43ef3.png)

**003**
![juju-example-003](https://user-images.githubusercontent.com/17748020/42946390-a43b6e16-8b62-11e8-9f43-bb95c0c3c88c.png)

**004**
![juju-example-004](https://user-images.githubusercontent.com/17748020/42946391-a47c5c00-8b62-11e8-9c29-b7916727c951.png)

**Comment by spencerbygraves** [comment]
@kwm14 I think we can keep it simple and not have any surrounding button. The 2px weight looks to light for this, especially when compared to the close icon here. I think 4px with 2px gap would be better.

The main decision is whether we have it vertical or horizontal. Horizontal looks like an ellipsis for more information, but vertical supports the direction that the menu, and any scrolling in that menu appears. So, I think that I favour vertical.

**Comment by kwm14** [comment]
## Updated designs
- Updated designs based on @spencerbygraves feedback
- Ready for review UXers on position preference 😃 
- Horizontal vs Vertical

### 005
![juju-example-005](https://user-images.githubusercontent.com/17748020/43000425-4572f982-8c19-11e8-8bc6-51f8080a649d.png)

### 006
![juju-example-006](https://user-images.githubusercontent.com/17748020/43000426-45976e34-8c19-11e8-927d-498d3f5e1c2c.png)

**Comment by matthewpaulthomas** [comment]
> @matthewpaulthomas in terms of the snapcraft.io prototype example, has this design been implemented?

The release UI design is currently [very different](https://github.com/CanonicalLtd/snap-squad/issues/586). And the latest iteration I see actually does use kebab icons as drag handles:

![vanilla-440-drag-1](https://user-images.githubusercontent.com/19801137/43002845-27dc4500-8c22-11e8-9ebd-8d9bcc147e20.png)

![vanilla-440-drag-2](https://user-images.githubusercontent.com/19801137/43002846-27f98fc0-8c22-11e8-8b86-91f3b94c762a.png)

I think it would be unfortunate for our icons for “drag this” and “this is a menu” to be identical except for the width of the blobs.

> I've had a browse of the market and these are the examples I've found:
>…
> Ant Design, GitHub and Trello

GitHub also uses cogwheel icons heavily for menus, such as on this very page:

![vanilla-244-cogwheel-menus](https://user-images.githubusercontent.com/19801137/43003097-1bad080e-8c23-11e8-8a9f-1251ed03a0d0.png)

(I don’t think it makes a difference that those menus include search fields.)

> Salesforce

Salesforce’s downward triangle is similar to the line-plus-triangle symbol in Windows ribbons:

![vanilla-244-windows-ribbon](https://user-images.githubusercontent.com/19801137/43003516-af9be4a8-8c24-11e8-8b95-a4efefcdd775.png)

Meanwhile, Windows toolbars use a double chevron:

![vanilla-244-windows-toolbar](https://user-images.githubusercontent.com/19801137/43003538-c0546108-8c24-11e8-97fe-d6318ed247d7.png)

So, there are many possibilities that aren’t three dots.

**Comment by Greggless** [comment]
👋 

What decade are these bad-boys from?
> ![vanilla-244-windows-ribbon](https://user-images.githubusercontent.com/19801137/43003516-af9be4a8-8c24-11e8-8b95-a4efefcdd775.png)
![vanilla-244-windows-toolbar](https://user-images.githubusercontent.com/19801137/43003538-c0546108-8c24-11e8-97fe-d6318ed247d7.png)

But I think they do show a good example of keeping the action in context. I also prefer the horizontal dots as they are more recognisable as a menu.

If the JuJu card-thingy has a title, or header area of some sort, these 'more' dots could be positioned in-line to keep them in context, otherwise they may seem a bit lost. Poor dots. 

Failing that, using a down chevron framed in a button could work, if less pretty.

**Comment by matthewpaulthomas** [comment]
Sources for the [ribbon](https://docs.microsoft.com/en-gb/windows/desktop/uxguide/cmd-ribbons) and [toolbar](https://docs.microsoft.com/en-gb/windows/desktop/uxguide/cmd-toolbars) graphics are both dated “31/05/2018”. 🤷‍♂️

> If the JuJu card-thingy has a title, or header area of some sort, these 'more' dots could be positioned in-line to keep them in context, otherwise they may seem a bit lost. Poor dots.
>
> Failing that, using a down chevron framed in a button could work, if less pretty.

_Maybe_, whatever icon we end up with, we could say:
- If it’s at the end of a narrow strip (e.g. a table cell), leave it borderless.
- If it’s not (e.g. Juju machine view), border it.

**Comment by Greggless** [comment]
> both dated “31/05/2018”

No way! I think I've been spoilt with Google's and MacOS design for too long...

**Comment by kwm14** [comment]
## Updated designs

Thanks for your feedback @matthewpaulthomas @Greggless you make valid points. I've updated the designs with 2 chevron styles that we could adopt. What do you think?

### 007
![context-menu-icon-007](https://user-images.githubusercontent.com/17748020/43081716-2c9e7224-8e8a-11e8-85ca-79aef98ea376.png)

![juju-example-007](https://user-images.githubusercontent.com/17748020/43081720-2fc09f9a-8e8a-11e8-809b-83f660b13b94.png)

### 008
![context-menu-icon-008](https://user-images.githubusercontent.com/17748020/43081758-454576f6-8e8a-11e8-8ed9-343ae5bfdf7b.png)

![juju-example-008](https://user-images.githubusercontent.com/17748020/43081766-48935a9e-8e8a-11e8-88ec-cf17e2f67fd6.png)

**Comment by kwm14** [comment]
In regards to `p-icon--contextual-menu` currently we will need to change the name based on it's use case.

 ![context-menu-icon](https://user-images.githubusercontent.com/19801137/39998147-1d1f221a-577d-11e8-85ef-0566d1b804ad.png)

I'm not sure on the best name as it can be used for reordering or drag and dropping between table rows. My naming proposal would be something simple like:

- `p-icon--reorder`

**Comment by Greggless** [comment]
I don't have a preference of the icon style, either is OK with me. But I do agree with MPT's comments:
> - If it’s at the end of a narrow strip (e.g. a table cell), leave it borderless.

This way the action remains in context of the content it relates to

> - If it’s not (e.g. Juju machine view), border it.

This'll make it look and feel much more like a button and be more visible.

<hr>

I think the naming convention could remain the same as it is doing the same job. But does this cause conflicts in the code?

`p-icon--reorder` seems fine to me!

**Comment by kwm14** [comment]
Issue created to update contextual-menu icon https://github.com/vanilla-framework/vanilla-framework/issues/1942 as well as updating the name of our current contextual-menu to the newly proposed above [here](https://github.com/vanilla-framework/vanilla-framework/issues/1943)
