### ISSUE TITLE
Make sure 3 ticks/checked patterns look different

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#25]
_From @yaili on June 1, 2017 14:10_

[Notes from the workshop](https://github.com/ubuntudesign/meeting-notes/issues/155):

- Make sure 3 patterns look different enough: checkbox, progress tick, marketing tick

_Copied from original issue: ubuntudesign/vanilla-store-theme-design#9_

**Comment by yaili** [comment]
As part of this issue, we should also assess the need for the "is-crossed" state, as mentioned in https://github.com/vanilla-framework/vanilla-framework/issues/1101

**Comment by matthewpaulthomas** [comment]
For reference, [the current `is-ticked` list item class](https://docs.vanillaframework.io/en/patterns/lists#list-with-icon):
![list with tick icons](https://user-images.githubusercontent.com/19801137/28321097-38aedd76-6bca-11e7-9fbc-fe9c8b4052f6.png)

Quite similar to the default appearance of a checkbox in Safari on iOS: 
![ios webkit checked](https://user-images.githubusercontent.com/19801137/28321275-c4c86de0-6bca-11e7-9335-abd1ec776961.png)

And differing only in size from [the progress tick](https://github.com/CanonicalLtd/juju-design/issues/229):
![juju setup checklist](https://user-images.githubusercontent.com/19801137/28321331-e5f345d0-6bca-11e7-92d3-61ac98129eb6.png)

**Comment by kwm14** [comment]
Removing from Epic and created a new issue [here](https://github.com/ubuntudesign/vanilla-design/issues/117).
