### ISSUE TITLE
Two levels of headers in Table of Contents

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#250]
- We need a better way of displaying hierarchy in the right hand Table of Contents
- Linked to the issue of indicating where a user is on a page example: https://elementary.io/docs/human-interface-guidelines#human-interface-guidelines
- Docs team issue report: https://github.com/juju/docs/issues/2847

**Comment by kwm14** [comment]
## Current menu level
- The main sections of docs are too similar to the standard headings
- 'About Juju', 'Quick Guides' and 'User Guide' is a whole new category, but it is visually the same as the subsection 'Clouds' below

![toc-current-001](https://user-images.githubusercontent.com/17748020/43208971-8351538a-9023-11e8-94f1-9afed04a2fba.png)

**Comment by kwm14** [comment]
## Examples in the field

### Ant Design
- Main section - 'Components'
- Sub section - 'General'

![ant-design](https://user-images.githubusercontent.com/17748020/43254719-e54d0dd0-90bf-11e8-870a-4853e9ec36fd.png)

### LDS
- Main section - 'Design Guidelines'
- Sub section - 'Overview'

![lightning-design-system](https://user-images.githubusercontent.com/17748020/43254491-695d734a-90bf-11e8-9156-64df0f7a163d.png)

### Material Design
- Main section - 'Material Foundation'
- Sub section - 'Foundation overview'

![material-design](https://user-images.githubusercontent.com/17748020/43254770-00302042-90c0-11e8-8930-237d8c59c593.png)

### Shopify
- Main section - 'Actions'
- Sub section - 'Account connection'

![shopify](https://user-images.githubusercontent.com/17748020/43254997-8a192cb8-90c0-11e8-952a-eaa815413038.png)

**Comment by kwm14** [comment]
## First exploration
- @spencerbygraves ready for first round review 😺 

**001**
- updated main section heading style to `p-muted-heading`
- cons: less prominence against sub sections (`0.875rem` vs `1rem`)

![toc-updated-001](https://user-images.githubusercontent.com/17748020/43317296-33fa114c-9194-11e8-996b-891b95e91e97.png)

**002**
- updated main section heading style to `h4`
- better type hierarchy between main and sub sections

![toc-updated-002](https://user-images.githubusercontent.com/17748020/43317419-9e684fbc-9194-11e8-9cce-dcfc55066db1.png)

**003**
- typographic treatment remains the same
- improve selected state on sub-sections

![toc-updated-004](https://user-images.githubusercontent.com/17748020/43317712-d2e92364-9195-11e8-9aba-ac70a951509c.png)

**004**
- update sub section font-color to match keyline selected state
- add background color to menu to highlight new color better

![toc-updated-005](https://user-images.githubusercontent.com/17748020/43317775-18793b30-9196-11e8-93e4-fe7daedca6b9.png)

**005**
- capitalise main section headings
- update font-size of third level menu items to `0.875rem`

![toc-updated-006](https://user-images.githubusercontent.com/17748020/43317832-4a29889c-9196-11e8-9eb0-199d8b3b0ee3.png)

**Comment by kwm14** [comment]
## Design review
_with @spencerbygraves_ 
- design concepts look amazing 😸 
- maybe we're over complicating the difference between main and sub sections
- agreed to move forward with this solution after discussion:
   - main section - `h5`
   - sub section - `p`
   - third level is hidden within an accordion
- next steps > update design to match review notes above

**Comment by kwm14** [comment]
## Updated design
- updated design based on design review feedback
- @spencerbygraves ready for re-review 😄 

### 006 - Default
![toc-updated-007](https://user-images.githubusercontent.com/17748020/43408804-24c5acc6-941a-11e8-9095-2ed1ef9e74dc.png)

### 006 - Open
![toc-updated-007-open](https://user-images.githubusercontent.com/17748020/43408817-2bd75dac-941a-11e8-99af-f9bf1eebf4e3.png)

**Comment by spencerbygraves** [comment]
👍

**Comment by kwm14** [comment]
Thanks @spencerbygraves I will create an issue in Documentation Builder repo so the template can be updated 💯
