### ISSUE TITLE
Create a small button

### ISSUE THREAD

**Issue by Caleb-Ellis** [ubuntudesign/vanilla-design#252]
@spencerbygraves commented on [Wed Jan 31 2018](https://github.com/vanilla-framework/vanilla-framework/issues/1559)

## Amendment

Buttons

## Context

It might be useful to have a smaller button size, which could also be used for the search box and form fields.

- The search box looks cramped in the [navigation bar](https://vanilla-framework.github.io/vanilla-framework/examples/patterns/search-box/navigation/)
- The tabs menu needed to be adjusted on the [resources page](https://www.ubuntu.com/resources)
- Jujucharms.com has a button in the header
- Might be useful in tables?

## Design TBC

![image](https://user-images.githubusercontent.com/9105999/35633386-00f9d256-06a1-11e8-814c-c86de5793c14.png)

---

@kwm14 commented on [Mon Feb 05 2018](https://github.com/vanilla-framework/vanilla-framework/issues/1559#issuecomment-363087699)

## Agreed in working group

- will it be a modifier or utility class
- @spencerbygraves @kwm14 to look at design spec
- explore different layouts
- buttons/forms/navigation/search box

---

@kwm14 commented on [Mon Feb 05 2018](https://github.com/vanilla-framework/vanilla-framework/issues/1559#issuecomment-363100903)

Design spec to be created before build can begin.

**Comment by kwm14** [comment]
@spencerbygraves with the recent release of v1.7.1 our button component paddings/margins have been updated, our default values now look like this (which fit inline with your proposal):

### v1.7.1 release
![button v1 7 0](https://user-images.githubusercontent.com/17748020/40928054-456d45ac-6818-11e8-8e74-b0083e77f3ac.png)

Also tested the button inside Juju navigation 💯 
### Juju navigation
![button v1 7 0 juju nav](https://user-images.githubusercontent.com/17748020/40928164-91e9f86c-6818-11e8-9698-536a1d8f1fd9.png)

**Comment by spencerbygraves** [comment]
@kwm14 thanks 👍
