### ISSUE TITLE
Product consistency: typography

### ISSUE THREAD

**Issue by spencerbygraves** [ubuntudesign/vanilla-design#272]
This is a task taken from our recent design workshop. [Notes can be found here](https://docs.google.com/document/d/1PRkiCvxWXGyxpMPAbnNPHT5A8DBiRuIUI536sGRAKAI/edit#heading=h.7ie3az4mukt6).

We discussed only using h3, h4, h5 and p in the products, and reserve h1 and h2 for brochure sites. The aim of this is to reduce vertical spacing and to decrease visual complexity in detailed products.

#### Things to consider

- Sizes
- Combination of sizes
- Use of headings in readme's
- Juju GUI details page header

**Comment by lyubomir-popov** [comment]
Attaching a few snapshots of MaaS headings 
![192 168 64 5_5240_maas_ 5](https://user-images.githubusercontent.com/2741678/40917641-e11419b2-67fb-11e8-8e6a-22ac7664f4a7.png)
![192 168 64 5_5240_maas_account_prefs_](https://user-images.githubusercontent.com/2741678/40917642-e12d0bac-67fb-11e8-8310-0f9576989e7d.png)
![192 168 64 5_5240_maas_accounts_ mzwkvtvt_view_](https://user-images.githubusercontent.com/2741678/40917644-e159c368-67fb-11e8-8951-8a77d70f7611.png)
![192 168 64 5_5240_maas_settings_users_](https://user-images.githubusercontent.com/2741678/40917645-e1751eba-67fb-11e8-9ec6-9af886448209.png)
![192 168 64 5_5240_maas_ 4](https://user-images.githubusercontent.com/2741678/40917646-e18a6e46-67fb-11e8-9a59-7c3f19672f58.png)
![192 168 64 5_5240_maas_ 3](https://user-images.githubusercontent.com/2741678/40917647-e1a35abe-67fb-11e8-8cef-efada101cede.png)
![192 168 64 5_5240_maas_ 2](https://user-images.githubusercontent.com/2741678/40917648-e1c0fd8a-67fb-11e8-8ad2-c9aa1ddbedae.png)
![192 168 64 5_5240_maas_ 1](https://user-images.githubusercontent.com/2741678/40917649-e1ea87d6-67fb-11e8-8cf5-7815df379ab5.png)







(before vanilla 1.7.*)

**Comment by spencerbygraves** [comment]
I have also tried only using h3 to p text sizes on some pages from Juju, which has shown that this could work there too. We have agreed in our design meetings to make this a recommendation to be added to the guidelines:

In our products we recommend only using h3, h4, h5 and p, reserving h1 and h2 for brochure sites. The aim of this is to reduce vertical spacing and to decrease visual complexity in detailed products.

H1 and h2 can be used if necessary but they should be kept to minimum.

(with example images)

**Comment by lyubomir-popov** [comment]
@spencerbygraves we also briefly discussed flipping the order in which you build the hierarchy - bottom up rather than top-down. This way, starting at p you only move up as many levels as needed, rather than starting at h1 and moving down a couple of levels, then going all the way down to p.

**Comment by spencerbygraves** [comment]
@lyubomir-popov Yes, thanks, we could add that to the recommendations.
