### ISSUE TITLE
Update code snippet

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#273]
Update code snippet to use $ icon, not on a grey background.

**Comment by kwm14** [comment]
## Current code-snippet component
![current-code-snippet](https://user-images.githubusercontent.com/17748020/41598569-6e5aac3c-73c8-11e8-8df0-d3ebdb0b00e1.png)

**Comment by kwm14** [comment]
### Updated code-snippet
- removed icon and added `$`
- using same font size and weight
- retained default icon-color: `$color-mid-dark`
- inherit new `neutral-button` hover state

![updated-code-snippet-003](https://user-images.githubusercontent.com/17748020/41605000-6731bae4-73d8-11e8-9477-faee07f72304.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍

**Comment by kwm14** [comment]
Thanks @spencerbygraves. Closing issue and have filed a bug for build [here](https://github.com/vanilla-framework/vanilla-framework/issues/1878).
