### ISSUE TITLE
Button update

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#278]
New button examples:
- With icon
- Contextual menu

**Comment by kwm14** [comment]
### Exploring padding/margin size
- explore two sizes for padding/margin between icon and text inside a button
- 8px vs 16px (vanilla-base-size)

![button-with-icon-001](https://user-images.githubusercontent.com/17748020/41919792-41f37a4a-7957-11e8-847c-8453b5416969.png)

- looking at the quick example I put together I think 8px/0.5rem would be the best value between icon and text. @spencerbygraves what do you think?

**Comment by spencerbygraves** [comment]
@kwm14 Yes, I think 8px looks better.

**Comment by kwm14** [comment]
### Snappy examples
- applying new icon in button component
- few instances of icon in button found on snappcraft.io and build.snapcraft.io

**snapcraft.io**
![button-with-icon-snapcrat io](https://user-images.githubusercontent.com/17748020/41969652-11a0213c-7a00-11e8-9fdb-5ba2d17467c2.png)

**build.snapcraft.io**
![button-with-icon-build snapcraft io](https://user-images.githubusercontent.com/17748020/41969660-1b783708-7a00-11e8-858d-e13f86d270ac.png)

**Comment by kwm14** [comment]
### Exploring just icon in button margins
- tested two sizes for margins left and right of icon inside a button
- 16px is our default margin left and right for buttons but wanted to test a smaller size
- @spencerbygraves what do you think?

![button-icon-001](https://user-images.githubusercontent.com/17748020/41975209-fbda630a-7a11-11e8-9d12-22c9f78cd892.png)

**Comment by kwm14** [comment]
### Juju examples
- applying only icon in button component
- few instances of solo icon in button found on elements of the GUI

**Juju GUI**
![button-with-icon-juju-gui](https://user-images.githubusercontent.com/17748020/41975487-be5ad892-7a12-11e8-919f-7e1e08baba6e.png)

**Comment by kwm14** [comment]
### Design review
_with @spencerbygraves_ 
- can we try `12p` margin and see how that looks too

**Comment by kwm14** [comment]
### Updated icon in button
- updated values to include `12px` example
- updated Juju GUI example too 

![button-icon-002](https://user-images.githubusercontent.com/17748020/42031110-fed6630e-7acc-11e8-82ea-f95d7487e75a.png)

### Juju GUI
![button-with-icon-juju-gui-002](https://user-images.githubusercontent.com/17748020/42031111-fefb665e-7acc-11e8-9e82-fd49c4173088.png)

**Comment by spencerbygraves** [comment]
@kwm14 I think 12px is best

**Comment by kwm14** [comment]
Thanks @spencerbygraves. Build issue created [here](https://github.com/vanilla-framework/vanilla-framework/issues/1902). Closing issue 💯
