### ISSUE TITLE
Design and propose new Community page 

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#279]
Original discussion and design exploration started [here](https://github.com/canonical-websites/vanillaframework.io/issues/109).

**Comment by spencerbygraves** [comment]
@kwm14 I think 001 works best. Thanks.

**Comment by kwm14** [comment]
Thanks. Build issue created [here](https://github.com/canonical-websites/vanillaframework.io/issues/141). Closing issue 💯
