### ISSUE TITLE
Design consistent headers across site pages

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#280]
Design consistent site page headers, similarity to other cloud marketing websites:
- https://jujucharms.com/how-it-works
- https://maas.io/install
- https://snapcraft.io/store

**Comment by kwm14** [comment]
### First exploration
- Taking influence from header styling on Juju, MAAS and Snapcraft
- Consistent gradient suru background as seen on homepage and docs

**/accessibility**

![accessibility-header](https://user-images.githubusercontent.com/17748020/41726867-f60dcb66-756a-11e8-8d7b-27065b9f4859.png)

**/browser-support**

![browser-support-header](https://user-images.githubusercontent.com/17748020/41726869-f6413e60-756a-11e8-8e11-e1e5bdfc2d80.png)

**/coding-standards**

![coding-standards-header](https://user-images.githubusercontent.com/17748020/41726871-f670df9e-756a-11e8-85e3-653759c09dd3.png)

**/contribute**

![contribute-header](https://user-images.githubusercontent.com/17748020/41726872-f69d8508-756a-11e8-8b7e-49e0bb6f3a59.png)

**Comment by spencerbygraves** [comment]
@kwm14 looks good 👍

**Comment by kwm14** [comment]
Thanks @spencerbygraves will use these headers when updating page layouts :smile

**Comment by kwm14** [comment]
Build issue created [here](https://github.com/canonical-websites/vanillaframework.io/issues/137) 💯
