### ISSUE TITLE
Design new layout on /accessibility 

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#281]
### Current page layout
![vanilla framework 9](https://user-images.githubusercontent.com/17748020/41858033-c22df0ae-7890-11e8-8720-48571b51a666.png)

**Comment by kwm14** [comment]
### Updated page layout

**001**
- 2-col layout
- question on hierarchy of type: starting with `h4` then going to `h3`?
- @spencerbygraves ready for visual review

![accessibility-001](https://user-images.githubusercontent.com/17748020/41902657-e56f338e-792b-11e8-8941-d306ad05026e.png)

**Comment by kwm14** [comment]
### Design review
_with @spencerbygraves_ 

- page looking good 👍 
- intro section update title from `h4` to `h3`
- intro copy update to 8-col and wrap bullets beneath

**Comment by kwm14** [comment]
Updated page layout
- changes made based on feedback
- @spencerbygraves ready for re-review

**002**
![accessibility-003](https://user-images.githubusercontent.com/17748020/41923388-33052314-795f-11e8-823b-af447e32b6c7.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍

**Comment by kwm14** [comment]
Thanks. Build issue created [here](https://github.com/canonical-websites/vanillaframework.io/issues/140). Closing issue 💯
