### ISSUE TITLE
Design new layout on /browser-support

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#282]
### Current page layout
![vanilla framework 8](https://user-images.githubusercontent.com/17748020/41773346-ae8737f6-7613-11e8-9e4c-318d4c16b18f.png)

**Comment by kwm14** [comment]
### Updated page layout
- Browser and operating systems currently out of date on the live site, so @Caleb-Ellis pointed me to the correct [document](https://github.com/canonical-webteam/practices/blob/master/coding/browser-support.md) for reference

**001**
- split content 6-col vs 6-col
- ticked list

![browser-support-001](https://user-images.githubusercontent.com/17748020/41784208-ecd39fea-7636-11e8-89d9-5ef3d061123a.png)

**002**
- split content 6-col vs 6-col
- default table

![browser-support-002](https://user-images.githubusercontent.com/17748020/41784228-fd03005e-7636-11e8-999a-949ea93cec9b.png)

**003**
- split content 6-col vs 6-col
- list with icons and dividers

![browser-support-003](https://user-images.githubusercontent.com/17748020/41784258-1156944e-7637-11e8-8314-952d2516156f.png)
 
- @spencerbygraves ready for first visual review 😺

**Comment by spencerbygraves** [comment]
@kwm14 In this case I think reading down the page in one column is best, like the original layout. I like seeing the browser icons at a glance, so maybe 003 but in one column.

If you want to use what looks like h4 for the first paragraph, we should do the same on [/coding-standards](#283).

Cheers

**Comment by kwm14** [comment]
### Updated page layout
- @spencerbygraves updated design based on feedback
- 003 preferred design but updated to one column layout
- ready for design re-review 👍 

**004**
![browser-support-004](https://user-images.githubusercontent.com/17748020/41845081-2716b2e8-786a-11e8-82dc-f029eeeb0bdd.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍

**Comment by kwm14** [comment]
Build issue created [here](https://github.com/canonical-websites/vanillaframework.io/issues/139). Closing issue 💯
