### ISSUE TITLE
Design new layout on /coding-standards

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#283]
### Current page layout
![screen shot 2018-06-22 at 11 01 44](https://user-images.githubusercontent.com/17748020/41771001-ae87683c-760b-11e8-8b26-6b02474d411c.png)

**Comment by kwm14** [comment]
### Updated page layout
- Not much content on the page but attempted to make it more visually pleasing
- Couple variations of layout/component types

**001**
- Updated header
- Removed bullet points
- Inline external links

![coding-standards-001](https://user-images.githubusercontent.com/17748020/41773111-d1a915ac-7612-11e8-8b47-cc0e5709b2c9.png)

**002**
- Updated header
- Basic card component to display linked content
- 6-col vs 6-col layout

![coding-standards-002](https://user-images.githubusercontent.com/17748020/41773115-d71bb4b8-7612-11e8-905d-605ce62dcd5f.png)

**003**
- Updated header
- Heading icon component
- 6-col vs 6-col layout w/divider

![coding-standards-006](https://user-images.githubusercontent.com/17748020/41773124-dd12fd4a-7612-11e8-8512-bf89c419116a.png)

- @spencerbygraves ready for first visual review pass 😺

**Comment by spencerbygraves** [comment]
@kwm14 thanks, 001 works for me.

**Comment by kwm14** [comment]
Thanks @spencerbygraves I've also updated intro paragraph as `h4` to match /browser-support design 👍 

**004**
![coding-standards-007](https://user-images.githubusercontent.com/17748020/41842810-b6ffbf5a-7863-11e8-86a0-17f7b6faa0f9.png)

**Comment by kwm14** [comment]
Build issue created [here](https://github.com/canonical-websites/vanillaframework.io/issues/137). Closing issue 💯
