### ISSUE TITLE
Grid: Check max-width values used on grids

### ISSUE THREAD

**Issue by therealjuan** [ubuntudesign/vanilla-design#289]
It will be good to double check and define max-width values for the different grid systems in Vanilla.

When using the values specified as max-width to replicate a similar looking grid on Sketch the numbers make it difficult to create a grid to work with even though code and visual designs doesn't need to use similar numbers as the generated code make use of %s.

Some examples on the values used by Vanilla:

### Maximum width of 1030 
For example when using:

- 1030 max-width
- 12 columns
- 24px each side of the grid
- 20px of space between columns

The calculated width for each column will be 67.5 px which make it difficult to replicate at some extent in Sketch even though we are using % on the code

If instead we used:
- 1036 max-width
- 12 columns
- 24px each side of the grid
- 20px of space between columns

The calculated width for each column will be 68px which will get us closer to have a similarly looking grid on our visual designs done in Sketch as well as in the generated code in the browser

### Maximum width of 990

Same thing happens when working with 990 whereas 988 seems like a more reasonable max-width value to use as it will give us a calculated width of 64px instead of 64.16px

**Comment by kwm14** [comment]
### Agreed in WG
- Proposed new grid size 👍 
- Look at grid defaults in the market

**Comment by kwm14** [comment]
### Grid proposal update
So taking what @therealjuan originally proposed, and findings from above frameworks I've amended a couple of max-widths across our breakpoints to fit better:

**1036px (currently 1030px)**
- `$breakpoint-large`
- `12-columns // 20px gutter-width // 24px margin-width`

![breakpoint-large](https://user-images.githubusercontent.com/17748020/42827913-652e16b2-89df-11e8-8057-93271aabcba7.png)

**772px (currently 768px)**
- `$breakpoint-medium`
- `8-columns // 20px gutter-width // 24px margin-width`

![breakpoint-medium](https://user-images.githubusercontent.com/17748020/42827927-6f0e06ec-89df-11e8-968e-08cd381c73c5.png)

**620px (no change)**
- `$breakpoint-small`
- `4-columns // 20px gutter-width // 24px margin-width`

![breakpoint-small](https://user-images.githubusercontent.com/17748020/42827934-731303d2-89df-11e8-854b-edbf41b71e29.png)

**460px (no change)**
- `$breakpoint-x-small`
- `4-columns // 20px gutter-width // 24px margin-width`

![breakpoint-x-small](https://user-images.githubusercontent.com/17748020/42827939-77eeabcc-89df-11e8-9cc8-cd42d8648d86.png)

@spencerbygraves what do you think? @Caleb-Ellis any room for concern over these numbers?

**Comment by spencerbygraves** [comment]
@kwm14 looks ok to me. Thanks.

**Comment by Caleb-Ellis** [comment]
@kwm14 @spencerbygraves @therealjuan No concern from me over the new numbers if it's just changing the default values of the breakpoints. My concern is with how we're currently calculating column widths since 1.7.0. As of https://github.com/vanilla-framework/vanilla-framework/pull/1408, column widths and gutters are calculated as a percentage of grid-max-width. Is the plan to remove fluid columns in favour of static 20px gutters? Or am I interpreting this wrong?

**Comment by kwm14** [comment]
@Caleb-Ellis great, yep it's just a change to max-widths on breakpoints. We're aren't suggesting to remove fluid columns as we know it currently works in % in Code 👍 

I will create an issue for breakpoints to be updated and I will then update the Grid in our Sketch file for Designers 😄

**Comment by kwm14** [comment]
Build update issue created here: https://github.com/vanilla-framework/vanilla-framework/issues/1931
