### ISSUE TITLE
Design Twitter stream image

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#292]
Create a default placeholder image to add to Twitter posts when we push out new release.

**Comment by kwm14** [comment]
- Use new gradient background and Suru folds
- Vanilla brand consistent styling
- Copy
   - Title: Latest release
   - Copy: vX.X.X

**Comment by kwm14** [comment]
### Initial designs

**001**
- `paragraph` font style

![vanilla-v1 8 0-release-001](https://user-images.githubusercontent.com/17748020/42687378-95d65132-8690-11e8-869a-1f784056c9db.png)

**002**
- `h6` font style

![vanilla-v1 8 0-release-002](https://user-images.githubusercontent.com/17748020/42687409-ac963f54-8690-11e8-97d2-963fe4ef57c3.png)

**003**
- `h5` font style

![vanilla-v1 8 0-release-003](https://user-images.githubusercontent.com/17748020/42687426-b4ab7650-8690-11e8-9bc4-a1457aa7ccdb.png)

@spencerbygraves any preference?

**Comment by spencerbygraves** [comment]
@kwm14 I quite like the way h6 goes with the thin font.

**Comment by kwm14** [comment]
@spencerbygraves perfect, that was my preferred choice too 👍
