### ISSUE TITLE
New proposal to left align icons

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#294]
_Notes from our Product consistency workshop:_
- Accordion
- Sidebar navigation components

**Comment by kwm14** [comment]
## First pass
- Left align icons on **Accordion** and **Table expandable**
- Applied to new MAAS filter

### Accordion
![000-left-align-accordion](https://user-images.githubusercontent.com/17748020/46150213-f901dd80-c263-11e8-8221-9d64f4c98d66.png)

### Table expandable
![001-left-align-expanded-table](https://user-images.githubusercontent.com/17748020/46150214-f901dd80-c263-11e8-8100-b48c617b35c3.png)

### MAAS filter
![002-left-align-accordion-maas](https://user-images.githubusercontent.com/17748020/46150215-f901dd80-c263-11e8-8921-d03fe0e30890.png)

**Comment by kwm14** [comment]
## Design review
_with @spencerbygraves @lyubomir-popov_ 
- Doesn't work for expandable table as we have instances where two items need to expand which live together (MAAS - MAC & IP)
- +1 new position for MAAS
- Try this new layout on RBAC and look for any other instances on marketing websites

**Comment by kwm14** [comment]
## Updated design
- Looked across our marketing sites and we don't use the accordion component
- Put MAAS example in situ
- Applied it to RBAC and also put in situ

### RBAC filter
![003-left-align-accordion-rbac](https://user-images.githubusercontent.com/17748020/46212929-25366080-c32f-11e8-9912-da92f7273981.png)

### RBAC in situ
![rbac-example](https://user-images.githubusercontent.com/17748020/46212931-25cef700-c32f-11e8-88a2-15c42f99bf4b.png)

### MAAS in situ
![maas-example](https://user-images.githubusercontent.com/17748020/46212930-25366080-c32f-11e8-84a1-d93b9cd59ae2.png)

**Comment by kwm14** [comment]
Will review with @clagom @cassiocassio next week when they're both back in the office 👍

**Comment by kwm14** [comment]
## UX review
- +1 from both @clagom and @cassiocassio 
- this update will be part of our v2.0 release
- future thoughts from @cassiocassio 
  - indicator on icon to know you've selected
  - icon darkens 10% or selection is framed?

**Comment by clagom** [comment]
@kwm14 +1, nice change

**Comment by kwm14** [comment]
I've created a build issue for this update to take place - https://github.com/vanilla-framework/vanilla-framework/issues/2008
