### ISSUE TITLE
Design releases.ubuntu.com homepage

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#299]
## Current homepage
![ubuntu releases](https://user-images.githubusercontent.com/17748020/44351016-b4cb3280-a498-11e8-8683-d7e05a01fc87.png)

**Comment by kwm14** [comment]
## First iteration of explorations
- Using current content on the site and applying Vanilla

### 001
![releases-homepage-001](https://user-images.githubusercontent.com/17748020/44519541-37383a00-a6c5-11e8-9f70-994f6ec484cb.png)

### 002
![releases-homepage-002](https://user-images.githubusercontent.com/17748020/44519542-37383a00-a6c5-11e8-9908-e3bcaeeebcd0.png)

### 003
![releases-homepage-003](https://user-images.githubusercontent.com/17748020/44519543-37d0d080-a6c5-11e8-9ab1-1e9ab858df36.png)

**Comment by kwm14** [comment]
## Design review
- **003** preferred design
- explore using `h4` for releases in hero section similar to style used on ubuntu.com

![screen shot 2018-08-23 at 11 14 01](https://user-images.githubusercontent.com/17748020/44519722-c0e80780-a6c5-11e8-9464-2cc5841327cd.png)
- rework layout of other Ubuntu releases section similar to style used on ubuntu.com

![screen shot 2018-08-23 at 11 15 50](https://user-images.githubusercontent.com/17748020/44519800-0278b280-a6c6-11e8-8aec-10449d7bd57a.png)
![screen shot 2018-08-23 at 11 15 59](https://user-images.githubusercontent.com/17748020/44519801-0278b280-a6c6-11e8-9fb7-96165040379f.png)

- remove external links as it's quite overwhelming

**Comment by kwm14** [comment]
## Updated designs
- taking feedback into consideration
- trialed a couple of versions for Ubuntu flavours section

### 004
![releases-homepage-004](https://user-images.githubusercontent.com/17748020/44529086-1aaafa80-a6e3-11e8-88c2-45c9e33f95ea.png)

### 005
![releases-homepage-005](https://user-images.githubusercontent.com/17748020/44529087-1b439100-a6e3-11e8-968a-02def80329c8.png)

### 006
![releases-homepage-006](https://user-images.githubusercontent.com/17748020/44529088-1b439100-a6e3-11e8-9853-e1344c409c0a.png)

**Comment by kwm14** [comment]
## Design review
- hero of **005** design
- ubuntu flavour section of **006** design

**Comment by kwm14** [comment]
## Updated design
- Taking feedback into consideration

### 007
![releases-homepage-007](https://user-images.githubusercontent.com/17748020/44537458-c578e400-a6f6-11e8-8a46-915f9e6aac77.png)

**Comment by anasereijo** [comment]
@kwm14 It's looking greatttt 👍
