### ISSUE TITLE
Design releases.ubuntu.com release landing template

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#300]
## Current landing template
![ubuntu 18 04 1 lts bionic beaver 1](https://user-images.githubusercontent.com/17748020/44530724-fa7d3a80-a6e6-11e8-9ffc-f1457bd1679e.png)

**Comment by anasereijo** [comment]
Hi @kwm14 this is looking so much better! 👍 

The only thing I'd suggest is maybe trying to separate a bit more the Desktop and Server download options by using basic cards? Unless you are trying to avoid the use of cards which is fair enough. I just think it might help to see quicker that you have 2 options for download.

Check [this](https://www.ubuntu.com/download) page (although I'd keep your font sizes it's looking so much better than this example)

Thanks for sharing this!

**Comment by kwm14** [comment]
## Updated design
- Taking feedback from @anasereijo into consideration
- Kept font sizes the same 😄 
- Updated download options to card style used on ubuntu.com for consistency, and looks much clearer to users that they're downloadable 👍 

### 002
![releases-landing-002](https://user-images.githubusercontent.com/17748020/44589528-ae96c800-a7b0-11e8-8e3f-ce8e54423329.png)
