### ISSUE TITLE
Create an audit of client logos across suite of websites

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#304]
## Google Doc
- https://docs.google.com/spreadsheets/d/16hagNOD461hNJo11GfSj_vy4rbOe0UBFHAEKnvxmlFk/edit#gid=0

**Comment by matthewpaulthomas** [comment]
- [www.ubuntu.com#3928](https://github.com/canonical-websites/www.ubuntu.com/issues/3928) AT&T logo stretched horizontally on /support

**Comment by kwm14** [comment]
Audit complete. I will now begin to update client logos into new template and file issues to update on relevant sites 👍
