### ISSUE TITLE
Update layout on /releases template

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#313]
## Current releases
![ubuntu manpage directory listing](https://user-images.githubusercontent.com/17748020/45827173-ca2cba00-bced-11e8-8258-c5f33438cede.png)

**Comment by kwm14** [comment]
## Simple updates
- Added ubuntu manuals logo
- Hero strip to show release as it's quite subtle using the nav to let you know
- Made the directory span across 12-cols to fit within grid
- @spencerbygraves ready for a swift review 😃 

![manpages u com-releases-001](https://user-images.githubusercontent.com/17748020/46527667-cb331f00-c889-11e8-8d39-16b2c7b36ab3.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍

**Comment by kwm14** [comment]
Build issue created [here](https://github.com/ubuntudesign/vanilla-squad/issues/409). Closing issue 👍
