### ISSUE TITLE
Device performance analysis

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#316]
Understand how well the site is optimised for devices and where we need/can make improvements.

**Comment by kwm14** [comment]
## Devices
Reviewing data since last release v1.8.0, 16 July.

1. Desktop - **88% users**
2. Mobile - **11% users**
3. Tablet - **1% users**

**Comment by kwm14** [comment]
## Screen resolution
With ongoing discussions amongst teams on viewports I thought it would be good to look at numbers, as most users use and view Vanilla on desktop this is the perfect opportunity to provide some stats.
1. 1920 x 1080 - **24% users**
2. 1366 x 768 - **16% users**
3. 1440 x 900 - **9% users**
4. 2560 x 1440 - **6% users**
5. 1680 x 1050 - **5% users**

## Browser
Good to see that our supported browsers we actively test on are users primary choice.
1. Chrome - **74% users**
2. Firefox - **13% users**
3. Safari - **7% users**

**Comment by clagom** [comment]
@lyubomir-popov @spencerbygraves 
This is very interesting, as we are also working on the navigation header across websites.
I see similar number across all Canonical websites by the way, data seems to be very consistent.
