### ISSUE TITLE
Content efficiency analysis

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#317]
Identify which pages are performing the best and which need a little optimization. 

- Which component content is most engaging?
- Are users clicking to see design specs?
- How well is the sidebar navigation structure working?

**Comment by kwm14** [comment]
## Content review
Reviewing data since last release v1.8.0, 16 July - 29 October.

### Components
We seem to be tracking an event for external links which feature heavily across the site from downloads to release notes to design specs.
- External link events - **971**
- Event actions - **18**

  - Design specs - **11**
  - Component examples - **3**
  - Release notes - **1**
  - Ubuntu typeface - **1**
  - GitHub - **1**
  - yarn - **1**

In terms of engagement Color, Animations and Navigation design spec have most interaction pulling in 37% of events.

**Comment by kwm14** [comment]
## Components
From review it's good to see that all components in the framework are getting some interactions, interesting to see which are more popular than others considering we use an identical template for each component.

### Top 5
1. Card
2. Grid
3. Navigation
4. Accordion
5. Buttons

**Comment by matthewpaulthomas** [comment]
> interesting to see which are more popular than others

A page could be more popular for a wide variety of reasons:
- The pattern itself is used more often. (Perhaps measure this by scraping the repos of known Vanilla-using sites. Then compare lookup vs. actual use.)
- The page covers multiple patterns. I think “Forms” is the odd one out here, covering eight different form controls as well as classes, while the Slider and Switch controls have pages to themselves.
- The pattern is ambiguously named (such as “Navigation”), so people wonder what it is, or think it’s something that it isn’t. (Measurable behaviour here would be spending a brief amount of time on the page, then going to another page for longer, then leaving the site.)
- The pattern is hard to use or remember.

>  slightly surprised by the lack of interaction for Code copyable and Code numbered

It might not even occur to authors that it would be better for a particular code block to be copyable or to have its lines numbered. So, how about combining those three into a single page?

**Comment by kwm14** [comment]
Thanks @matthewpaulthomas for your comments.

Good idea on looking into the pattern further by scraping repos of known Vanilla-using sites 👍 

Agree with your last comment on combining code examples onto one page, I'll create an issue for this update to be made for v2.0 release 😄

**Comment by kwm14** [comment]
## Vanilla-using sites
GitHub scrape to see compare views of the Top 5 components above vs code usage in sites.

### Top 5
1. Navigation - **3,190 code results**
2. Card - **123 code results**
3. Buttons - **107 code results**
4. Accordion - **95 code results**
5. Grid - **2 code results (page structure must be laid out using rows (.row))**

This is a bigger piece of work which I'd like to investigate with a deeper dive into GA and further comparisons of views vs usage 😄
