### ISSUE TITLE
Inner shadows on forms proposal

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#319]
Discussed in weekly Design review with @spencerbygraves @lyubomir-popov @anasereijo 
- do we need inner-shadow on forms
- look at forms across Cloud applications
- look at other example form fields and see how they're styled

**Comment by clagom** [comment]
Slightly related, but I do wonder if we need inner-shadow on drop-downs. If we keep inner shadows in form fields, maybe a good visual distinction to remove it from drop-down elements:
<img width="253" alt="screenshot 2018-10-04 at 12 07 06" src="https://user-images.githubusercontent.com/1953388/46470311-112aad00-c7ce-11e8-9da8-bebc4b787c1d.png">

**Comment by kwm14** [comment]
Thanks @matthewpaulthomas when we plan this work into an iteration I will reference your comments made 👍

**Comment by matthewpaulthomas** [comment]
Sorry to pile on, but there was a relevant incident during Canonical’s roadmap sprint this week. One session (reviewing a Snap Store moderation UI) was diverted for a minute when someone asked why a particular piece of data was editable. It turned out that it wasn’t editable, it was in a Vanilla text field that was disabled. But it was the only text field in view, and it wasn’t obvious that it _was_ disabled.

Often when we design enabled and disabled states, we have them on screen at the same time for comparison, so it’s obvious which is which. But it’s important for a control’s state to be obvious even when you don’t have the other state to compare to. The more ways that enabled and disabled controls differ — shadow or not, border color, background color — the easier it is to tell.

**Comment by kwm14** [comment]
Thanks @matthewpaulthomas for further comments from the sprint 👍

**Comment by kwm14** [comment]
## Review of components

### Buttons
- Base / Brand / Negative / Neutral / Positive - No box shadow

### Forms
- Fieldset - `Box shadow: inset 0 1px 1px rgba(0,0,0,.12)`
- Input - `Box shadow: inset 0 1px 1px rgba(0,0,0,.12)`
- Multiple select - `Box shadow: inset 0 1px 1px rgba(0,0,0,.12)`
- Validation - `Box shadow: inset 0 1px 1px rgba(0,0,0,.12)`
- Selects - `Box shadow: inset 0 1px 1px rgba(0,0,0,.12)`

### Controls
- Checkboxes - No box shadow
- Radio buttons - No box shadow
- Search box - No box shadow
- Slider - No box shadow
- Switch - `Box shadow: inset 0 2px 5px 0 hsla(0,0%,7%,.2)`

**Comment by kwm14** [comment]
## Design exploration
Couple of variations based on comments above 

### 001
- Box shadow on input fields (Fieldset, Input, Multiple select,Validation and Search
- No shadow on checkboxes, radio buttons, dropdown and slider

![box-shadow-components-002](https://user-images.githubusercontent.com/17748020/49089790-3549be00-f254-11e8-8d23-be2ccd457bf6.png)

### 002
- Based on my example [investigation](https://github.com/ubuntudesign/vanilla-design/issues/333) most systems either have shadow or not across all for consistency 
- No box shadow applied to all forms and controls

![box-shadow-components-003](https://user-images.githubusercontent.com/17748020/49090049-cf116b00-f254-11e8-87e7-5cdc988f3394.png)

**Comment by spencerbygraves** [comment]
I also had a quick look at this recently.

![image](https://user-images.githubusercontent.com/9105999/49093173-785b5f80-f25b-11e8-9838-babca9296b37.png)

**Comment by clagom** [comment]
I do find the default state a bit too faded out in these examples (meaning greyed out). A bit too easy to confuse it for a disabled field probably?

**Comment by spencerbygraves** [comment]
@clagom for comparison it's darker than what we have at present, but we can try other colours.

Current version uses #CDCDCD as below 

![image](https://user-images.githubusercontent.com/9105999/49094615-9080ae00-f25e-11e8-9400-f01520d5f9a7.png)

**Comment by clagom** [comment]
If the shadow is removed, I think it may need a darker border (maybe just a bit more in order to improve the contrast between default and disabled)

**Comment by kwm14** [comment]
> @clagom for comparison it's darker than what we have at present, but we can try other colours.
> 
> Current version uses #CDCDCD as below
> 
> ![image](https://user-images.githubusercontent.com/9105999/49094615-9080ae00-f25e-11e8-9400-f01520d5f9a7.png)

Currently in Vanilla the border is set to #CDCDCD but we recently [updated](https://github.com/vanilla-framework/vanilla-framework/pull/1984) the border color to #999 which will be in next release 2.0. Original design issue [here](https://github.com/vanilla-framework/vanilla-framework/issues/1933).

**Comment by kwm14** [comment]
## 50 shades of grey
@clagom @spencerbygraves 

- box-shadow removed
- applied remaining darker greys in palette

![box-shadow-components-004](https://user-images.githubusercontent.com/17748020/49096494-92e50700-f262-11e8-8a91-7d664ab62917.png)

**Comment by kwm14** [comment]
## Review
Agreed with @clagom @spencerbygraves for me to create a demo of options the options above to see form fields and buttons in situ 👍
