### ISSUE TITLE
Update style of inline code component

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#329]
## Current styling 
![screenshot 2018-10-24 at 10 40 45](https://user-images.githubusercontent.com/17748020/47421836-501ea380-d779-11e8-9a63-6455853dedca.png)

**Comment by kwm14** [comment]
## Examples of inline code

### GitHub
![github-inline-code](https://user-images.githubusercontent.com/17748020/47423647-7f371400-d77d-11e8-8df3-fe25dc7ce56f.png)

### Bulma
![bulma-inline-code](https://user-images.githubusercontent.com/17748020/47423646-7f371400-d77d-11e8-93e2-daf4a9e16948.png)

### Salesforce
![lightning-design-inline-code](https://user-images.githubusercontent.com/17748020/47423648-7f371400-d77d-11e8-96a5-735e1564bf8e.png)

### Ant Design
![antdesign-inline-code](https://user-images.githubusercontent.com/17748020/47423691-970e9800-d77d-11e8-94ce-955a63c891ed.png)

### Google
![google-inline-code](https://user-images.githubusercontent.com/17748020/47423694-97a72e80-d77d-11e8-8d04-d404130c78ff.png)

### MailChimp
![mailchimp-inline-code](https://user-images.githubusercontent.com/17748020/47423696-97a72e80-d77d-11e8-8356-1f7a10a46b5f.png)

### Marvel
![marvel-inline-code](https://user-images.githubusercontent.com/17748020/47423698-97a72e80-d77d-11e8-8070-8cfd72bddd5c.png)

### Sky
![sky-inline-code](https://user-images.githubusercontent.com/17748020/47423700-983fc500-d77d-11e8-8ff2-bf07d4f9102a.png)

**Comment by kwm14** [comment]
## Review
- some good examples out there
  - coloured backgrounds
  - coloured text
  - bigger font-size
- we have a small color palette so will explore our current palette and also our new greys recently added for v2.0 release

```
$color-x-light:          #fff !default;
$color-light:            #f7f7f7 !default;
$color-mid-x-light:      #e5e5e5 !default;
$color-mid-light:        #cdcdcd !default;
$color-mid:              #999 !default;
$color-mid-dark:         #666 !default;
$color-dark:             #111 !default;
$color-x-dark:           #000 !default;
```

**Comment by kwm14** [comment]
## Initial design concepts
Few designs using our current color palette whilst making sure text vs background is AAA accessible.

### 001
- no padding top/bottom so line height remains consistent
- padding `0.25rem` left and right of container
- background color `#e5e5e5`
![inline-code-001](https://user-images.githubusercontent.com/17748020/47426699-dc36c800-d785-11e8-8956-8fb136fc599f.png)

### 002
- container styling same as 001
- background color `#cdcdcd`
![inline-code-002](https://user-images.githubusercontent.com/17748020/47426700-dc36c800-d785-11e8-981b-3858a583dc01.png)

### 003
- container styling same as 001
- inherit `p-button--neutral` style
![inline-code-003](https://user-images.githubusercontent.com/17748020/47426701-dc36c800-d785-11e8-8e84-a249c8848cd6.png)

### 004
- container styling same as 001
- introduced `$color-information` text from our palette due to us providing info on code to use
- background color `#f7f7f7`

![inline-code-004](https://user-images.githubusercontent.com/17748020/47426702-dc36c800-d785-11e8-9370-82f899f6c347.png)

### 005
- no container
- text color `#335280` same as 004

![inline-code-005](https://user-images.githubusercontent.com/17748020/47426703-dccf5e80-d785-11e8-9eac-ece2d5620e5b.png)

**Comment by kwm14** [comment]
@spencerbygraves ready for first review 👍

**Comment by spencerbygraves** [comment]
@kwm14 001 looks good to me.

**Comment by kwm14** [comment]
Thanks @spencerbygraves 👍 

@nottrobin @anthonydillon want to check with a developer on this design, are you happy with **001** design?

**Comment by nottrobin** [comment]
Yeah I think 001 looks fine.

**Comment by nottrobin** [comment]
I quite like 004 as well

**Comment by kwm14** [comment]
Thanks @nottrobin I also liked **004** but I just realised that our `#f7f7f7` grey sometimes isn't visible on screens as it's so light so may end up just with the blue text.

So for now I think it's best to move forward with **001** 💯

**Comment by kwm14** [comment]
Will revise MD and create a build ticket for this component to be updated 👍
