### ISSUE TITLE
Accessibility outline design proposal

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#331]
Reference investigated examples here: https://github.com/ubuntudesign/vanilla-design/issues/330

**Comment by kwm14** [comment]
## First iteration of designs
Focus state outlines based on WG agreed proposal. @spencerbygraves @lyubomir-popov inital review ready for your eyes 😃 

### 001
- Keeping to our existing design but removing `2px` radius around form field
- Focus state overrides error on click
- Design still accessible due to icon and error message in bold
![accessible-focus-state-001](https://user-images.githubusercontent.com/17748020/47649122-23e99500-db74-11e8-8724-1937069caa5a.png)

### 002
- Focus state overrides error on click
- Introduce 40% accessible background color on form field when notification occurs
- Focus state and error still both visible
![accessible-focus-state-002](https://user-images.githubusercontent.com/17748020/47649124-23e99500-db74-11e8-8016-2a3b93487e2b.png)

### 003
- Introduce `2px` outer glow on focus state as an extra level
- Once error occurs border is updated to reflect notification but focus outer glow indicator remains
![accessible-focus-state-003](https://user-images.githubusercontent.com/17748020/47649125-23e99500-db74-11e8-9eea-c7503403bed9.png)

**Comment by lyubomir-popov** [comment]
@kwm14 @spencerbygraves I think both 001 and 002 work. no strong preference either way; as to 003, it would still lead to clipping when the parent container is set to overflow: hidden;

**Comment by spencerbygraves** [comment]
@kwm14 I like 001. I agree with @anthonydillon that the focus state becomes less visible in version 002.

**Comment by kwm14** [comment]
Great, thanks for all your feedback 👍 looks as if **001** is the preferred solution going forward 💯

**Comment by kwm14** [comment]
I will create an Epic for this piece of work including updated design spec and build 👍
