### ISSUE TITLE
Could we add the Vanilla logo to the storybook examples page?

### ISSUE THREAD

**Issue by carlaberkers** [ubuntudesign/vanilla-design#337]
Great job adding Vanilla Framework to https://storybook.js.org/examples/ !

I was thinking it would be nice to have the logo there as well, would it be easy to add to the nice orange image?

**Comment by kwm14** [comment]
## PR
Filed here awaiting approval https://github.com/storybooks/storybook/pull/5182

## Thumbnail
![vanilla](https://user-images.githubusercontent.com/17748020/50829393-49e1a180-133c-11e9-836e-fdaae3dd4139.png)

**Comment by kwm14** [comment]
Approved by Storybook 👍 and will be landed soon.
