### ISSUE TITLE
Gallery pattern proposal

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#36]
@spencerbygraves can you add the examples here?

- maas.io tour
- juju bundle details

**Comment by kwm14** [comment]
### maas.io tour
![maas io-gallery](https://user-images.githubusercontent.com/17748020/28326586-0e744d34-6bd9-11e7-83bf-7c3133a909b1.png)

### Juju bundle details
![bundle details - fullscreen](https://user-images.githubusercontent.com/17748020/28326723-71df0800-6bd9-11e7-93a0-970f26b190d5.png)

**Comment by anthonydillon** [comment]
We have agreed this is required in Vanilla but the build will be discussed in the dev catch up.

**Comment by kwm14** [comment]
@anthonydillon do you have an update on this issue discussed in Dev catch or meeting notes I can reference?

**Comment by anthonydillon** [comment]
There has been no discussion on the implementation. I will discuss with the team shortly.

**Comment by kwm14** [comment]
@anthonydillon any further update on this regarding build?

**Comment by anthonydillon** [comment]
I don't think we will be doing this for sometime. It takes a lot of
functionality. I think internally we should just copy what was done on
maas.io.

**Comment by kwm14** [comment]
Ok sure. Will keep this item in the backlog so it's tracked for future.
