### ISSUE TITLE
Radio menus <select> are slightly different height from text fields and buttons

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntudesign/vanilla-design#37]
In Vanilla by default, text fields and buttons are the same height, but radio menus `<select>` are taller. This makes them look wonky alongside each other. They should default to the same height.

The default heights:
- Text field: height = `line-height` + `padding` + `border` = (browser default font size 16px × `body`…`1.5`) + (2 × 8px) + (2 × 1px) = **42px**
- Button: height = `line-height` + `padding` + `border` = 16px + (2 × 12px) + (2 × 1px) = **42px**
- Radio menu: height = max(`min-height`, intrinsic height) = max(`48px`, (`line-height` + `padding` + `border`)) = max(48px, (19px + (2 × 8px) + (2 × 1px)) = max(48px, 37px) = **48px**

Vanilla defaults to specifying that “[Labels and most input types are 100% width of the `<form>` parent element](https://docs.vanillaframework.io/en/base/forms)”. So though they retain the browser’s `display: inline`, they are on a line by themselves.

But regardless of whether _that_ is a good default, in real-world forms it is common for radio menus to be alongside text fields and/or buttons. For example:

- [A design sketch for Maas](https://github.com/CanonicalLtd/MAAS-design/issues/138):
  ![a radio menu for grouping search results, followed by a text field for the search string.](https://user-images.githubusercontent.com/19801137/28261190-23371458-6ad6-11e7-92af-7fc86811c20d.png)

- [Another design sketch for Maas](https://github.com/CanonicalLtd/MAAS-design/issues/104):
  ![a “Subnet” radio menu, followed by text fields for “Start ID” and “End ID”.](https://user-images.githubusercontent.com/19801137/28269524-504a5990-6afa-11e7-8c35-69557959509d.png)

- [A mockup for Juju](https://github.com/CanonicalLtd/juju-design/issues/229):
  ![A “Source:” radio menu, followed by a text field and an “Add key” button.](https://user-images.githubusercontent.com/19801137/28269953-b1cb0b3c-6afb-11e7-842e-abdc9e458246.png)

If these controls were alongside each other but slightly different heights, they would look wonky. And if their heights were customized just for these situations, they would be inconsistent with other radio menus on the same page.

Therefore, radio menus should default to having the same height as text fields and buttons.

**Comment by MariaVrachni** [comment]
+1

note: Juju has completely different input fields than MAAS. In Juju the label is in the field and moves to the top left when the user clicks in (these fields can be found in material design)

**Comment by anthonydillon** [comment]
Fields should be the same height.
