### ISSUE TITLE
Bigger button style

### ISSUE THREAD

**Issue by bartaz** [ubuntudesign/vanilla-design#41]
On https://build.snapcraft.io landing page we use bigger call to action buttons:

<img width="1065" alt="screen shot 2017-07-21 at 12 56 55" src="https://user-images.githubusercontent.com/83575/28461261-19826ef6-6e16-11e7-8b39-7a5d7b89eeb9.png">

Currently we need to add custom style to it, but possibly it would be good to include as a standard Vanilla style to be used on other sites as well.

It should work with all available button styles (positive, negative, base, etc), so it could be implemented as `is-bigger` state class (similar to existing `is-inline`).

**Comment by yaili** [comment]
There is something like this in the brochure theme, would that help? https://github.com/vanilla-framework/vanilla-brochure-theme/blob/develop/scss/_patterns_buttons.scss

**Comment by Lukewh** [comment]
Should use the larger button as in brochure theme, but should be moved in to vanilla.

**Comment by kwm14** [comment]
## Visual design

- Brochure theme is no longer supported but looking at the .scss of `is-bigger` styles for the button they don't seem to match what is seen on [build.snapcraft.io](https://build.snapcraft.io/)
- So I based padding and text styles seen on live version

![screen shot 2017-11-28 at 14 41 00](https://user-images.githubusercontent.com/17748020/33325593-9d90ff56-d44a-11e7-93ea-54d619a72b9f.png)

### 001
![vanilla-button-styles](https://user-images.githubusercontent.com/17748020/33325840-52662e38-d44b-11e7-847d-d2bae7df0649.png)

**Comment by kwm14** [comment]
## Visual review

- Discussion with @spencerbygraves 
- As this is a one-time use case using a larger button style on a website it won't be pushed up to Vanilla
- If a `is-bigger` button is used somewhere else in a web application or marketing site we will revisit this issue
