### ISSUE TITLE
Lists with green ticks

### ISSUE THREAD

**Issue by bartaz** [ubuntudesign/vanilla-design#43]
In https://build.snapcraft.io we green ticks in list on landing page (as standard Vanilla grey ticks were confusingly similar to checkboxes):

<img width="1046" alt="screen shot 2017-07-24 at 10 00 51" src="https://user-images.githubusercontent.com/83575/28522606-fa23bc8a-7078-11e7-8f9d-4ca7ce27955e.png">

This seems to be related to #25 (or maybe even duplicate of it).

**Comment by Lukewh** [comment]
Bump over to UX/ Design, including @yaili

**Comment by anthonydillon** [comment]
We now have use the `$color-accent` to style small elements such as ticks. I know the icon it slightly different but I believe we should use the same tick icon across all sites.

Would just changing the accent colour too green and using the Vanilla tick icon work?

**Comment by kwm14** [comment]
Issue will be followed up [here](https://github.com/ubuntudesign/vanilla-design/issues/117)
