### ISSUE TITLE
Update notification design spec with dismiss icon

### ISSUE THREAD

**Issue by bartaz** [ubuntudesign/vanilla-design#44]
Current notification pattern only has a text link as an action.

In build.snapcraft.io we already have text link to survey in notification text which could be easily confused with another inline 'Dismiss' link, so we introduced a dismiss icon to notification:

<img width="1047" alt="screen shot 2017-07-21 at 15 42 37" src="https://user-images.githubusercontent.com/83575/28522729-83f40870-7079-11e7-8ea8-0cfae75336d3.png">

This could probably we worth including in Vanilla pattern as an option.

**Comment by Lukewh** [comment]
Design/ UX to review the various differences across products/ sites.

**Comment by kwm14** [comment]
## Investigation
Investigation across sites and design next steps found [here](https://github.com/ubuntudesign/vanilla-design/issues/137).

**Comment by kwm14** [comment]
## Design update

- default notification with dismiss/close icon
- large and small screen version

### 001
![default-notification](https://user-images.githubusercontent.com/17748020/33553070-2a43a860-d8ef-11e7-99e5-39289134b193.png)

**Comment by spencerbygraves** [comment]
If Vanilla ever has grouped notifications, the existing designs would also need updating. Here they are for reference:

![image](https://user-images.githubusercontent.com/9105999/33562887-5e7ba12c-d90e-11e7-835f-ee65fc7c9933.png)

**Comment by kwm14** [comment]
@spencerbygraves ok great thanks for sending through designs for Grouped notifications. Are we using these in Juju currently?
