### ISSUE TITLE
Incorrect Docs link in description

### ISSUE THREAD

**Issue by p-racoon** [ubuntudesign/vanilla-design#451]
**Describe the bug**
The docs link mention [here](https://github.com/canonical-web-and-design/design-vanilla-framework) is not available I think the  correct link whould be https://vanillaframework.io/docs .
![image](https://user-images.githubusercontent.com/13845070/120091600-41b37800-c12a-11eb-9a86-2091611cad57.png)

**To Reproduce**
1. Go to 'https://github.com/canonical-web-and-design/design-vanilla-framework'
2. Click on `'docs.vanillaframework.io/en/'` provided on the right side.
3. The link would return a 404

**Expected behavior**
It should have taken to the vanillaframework docs page.

**Screenshots**
The Error
![image](https://user-images.githubusercontent.com/13845070/120091639-b4bcee80-c12a-11eb-89cb-cc24e229330e.png)

**Additional context**

**Comment by bartaz** [comment]
Thank you, this repo is quite outdated and we don't maintain it actively, so we haven't noticed that. Fixed.
