### ISSUE TITLE
Add cross icon to list pattern - neutral version

### ISSUE THREAD

**Issue by cristinadresch** [ubuntudesign/vanilla-design#452]
[Related to issue 3405](https://app.zenhub.com/workspaces/-vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/3405)

Explore a neutral version, grey component (and specify when to use this neutral version instead of green/red). Opening a different ticket for this

**Comment by anasereijo** [comment]
Next steps to be discussed in the WG
[Miro board](https://miro.com/app/board/o9J_lvhHnQc=/)

- Change specs? where? 
- Create specs?
- Post in Discourse?
- Create UI issue?

**Comment by clagom** [comment]
WG: to present this in the design assembly and discuss UX wise
