### ISSUE TITLE
New badge component - specs

### ISSUE THREAD

**Issue by cristinadresch** [ubuntudesign/vanilla-design#455]

**Comment by rayito** [comment]
[New component specs doc](https://docs.google.com/document/d/1ofb6S7XLq7lVg32uSHaLxsmSy8eBBvKpeZHe2FQEdhU/edit?usp=sharing)

**Comment by lyubomir-popov** [comment]
LGTM, thanks @rayito.

**Comment by ziheliu214** [comment]
@rayito sorry! Think the documentation needs slightly more work. Left comments in the doc, please let me know if you have any questions

**Comment by ziheliu214** [comment]
@clagom Just checking, since this documentation is only about badges, will we have a new documentation on chips in the pipeline?

**Comment by rayito** [comment]
> @rayito sorry! Think the documentation needs slightly more work. Left comments in the doc, please let me know if you have any questions

I agree with the comments, I didn't know the anatomy section was going to grow until I felt it needed explanations, so I guess it's better to describe the variants; although I don't think there are 3 variants. 

The badge with less than 999 is not a design variant, it's just how it behaves according to the content. I think there are 2 variants as I commented in the doc: the one that shows large numbers as 999+ and the one that shows large numbers with a rounding plus a decimal unit prefix.

**Comment by rayito** [comment]
I have rewritten the doc considering @ziheliu214 's comments, please have a look.

[Vanilla #455 - New badge component](https://docs.google.com/document/d/1ofb6S7XLq7lVg32uSHaLxsmSy8eBBvKpeZHe2FQEdhU/edit?usp=sharing)

**Comment by cristinadresch** [comment]
@elioqoshi can you have a look please?

**Comment by elioqoshi** [comment]
@rayito This generally looks good to me! I just have a small concern with rounding numbers up. So going from 1790 to 1800 for example. Would there be any instance where this would be problematic? I mean there might be cases where one should not overestimate a specific number, especially when it might be resource related (for example: if my allowance is 1800 machines and I have 1790, I still am able to have 10 more machines. If it shows like 1.8k currently, I might think I need a bigger allowance, no? Or am I reading too much into it?

Also, if this will go straight into discourse, we might avoid sentences like this in the documentation:

> After a workshop to decide the future of the Label component, we made the following decisions:

**Comment by elioqoshi** [comment]
@rayito Let us know when you update the specs so we can +1 :)

**Comment by rayito** [comment]
@elioqoshi I added a paragraph in the `When not to use` section, please let me know if you would write it differently.

**Comment by elioqoshi** [comment]
LGTM!
