### ISSUE TITLE
Ensure labels dont look clickable - Visual

### ISSUE THREAD

**Issue by cristinadresch** [ubuntudesign/vanilla-design#461]
Labels are not clickable (if you need clickable, you need to use chips) so we need to ensure labels don't look like they can be clickable

**Comment by lyubomir-popov** [comment]
For reference - https://app.zenhub.com/workspaces/-design-system-tribe-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/4367

**Comment by lyubomir-popov** [comment]
Proposal:

![image](https://user-images.githubusercontent.com/2741678/161941769-85ddbcc1-d2f6-4473-b27a-5c78f5b409c0.png)

**Comment by elioqoshi** [comment]
No one had any complaints so let's close this
