### ISSUE TITLE
Navigation pattern needs to show current highlighted page and rollover state

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-design#50]
The current navigation pattern does not cater for a hover state. It also needs to a state to highlight the current page.

**Comment by kwm14** [comment]
### Vanilla working group

- Approved
- Reference Joana's [design](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/60)
- Design spec

**Comment by kwm14** [comment]
## Visual design

- Joana's above exploration was more focused to Ubuntu
- Inherited hover and selected states from our [Tabs](https://docs.vanillaframework.io/en/patterns/tabs) navigation
- hover state: `$color-light`
- selected state: `$color-mid-dark`

### 001
![global-navigation-states](https://user-images.githubusercontent.com/17748020/33316305-69f8c63e-d42b-11e7-8588-b0fa650e0cec.png)

**Comment by kwm14** [comment]
Updated design spec [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Navigation) and will create issue for Dev to implement in build.
