### ISSUE TITLE
Card pattern should reference 'header', not 'heading'

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-design#51]
In this [spec](https://github.com/ubuntudesign/vanilla-design/tree/master/Card), it's confusing that there are specific styles against 'heading' as that typically refers to h1, h2 etc 

The nomenclature here should refer to 'header'

**Comment by kwm14** [comment]
Design spec and md file updated so it references 'header', not 'heading'.

- [Design spec](https://github.com/ubuntudesign/vanilla-design/blob/master/Card/card.png)
- [Mark down file](https://github.com/ubuntudesign/vanilla-design/blob/master/Card/card.md)
