### ISSUE TITLE
Check boxes have no active state

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-design#53]
The vanilla checkboxes have no active state.

- Go to https://vanilla-framework.github.io/vanilla-framework/examples/base/forms/checkboxes/
- Click tab a few times and you have no idea when you are on a checkbox

**Comment by kwm14** [comment]
Design spec can be found [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Focus%20state).

**Comment by kwm14** [comment]
Focus styling for MAAS created by Rich can be found [here](https://github.com/ubuntudesign/maas-gui-vanilla-theme/blob/master/scss/_base.forms.scss) for reference when building.

**Comment by kwm14** [comment]
Closing. Development work carried out here #1367
