### ISSUE TITLE
Colors out of date

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-design#6]
vanilla-design/Color/color.png

Missing: 
- Blue for focus (and uncommitted)
- Blue for components
- Text colour #111

**Comment by jamiedawsonyoung** [comment]
Link to the issue: https://github.com/CanonicalLtd/MAAS-design/issues/83

**Comment by yaili** [comment]
We agreed we were not going to add focus blue in Vanilla, only in dashboard/cloud theme for now.

**Comment by jamiedawsonyoung** [comment]
Sorry, my mistake. The other changes are still needed though?

**Comment by yaili** [comment]
Updated now, sorry I should have read my own sprint notes ;)
