### ISSUE TITLE
Exploration of downloads section

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#70]
## Users able to download resources and tools:

- Vanilla library
- Sketch template
- Vanilla logo?
- Plugins?
- Future design linking to React?

**Comment by kwm14** [comment]
## Examples

- Ant Design - https://ant.design/docs/resource/download
- Carbon Design - http://carbondesignsystem.com/resources
- Apple - https://developer.apple.com/design/resources/
- Atlassian - https://atlassian.design/guidelines/marketing/resources/logo-files
- Shopify - https://polaris.shopify.com/resources/resources

**Comment by kwm14** [comment]
## Visual exploration

- promote available resources for users: design and build
- 4 variations of layout
- using existing Vanilla components

### 001
![resources-001](https://user-images.githubusercontent.com/17748020/30116737-3f992006-9316-11e7-820a-ed575fb5dce9.png)

### 002
![resources-002](https://user-images.githubusercontent.com/17748020/30116754-464f92b8-9316-11e7-87cd-7feb298d5b80.png)

### 003
![resources-003](https://user-images.githubusercontent.com/17748020/30116766-4b21fa88-9316-11e7-836d-cc3d50ae6561.png)

### 004
![resources-004](https://user-images.githubusercontent.com/17748020/30116777-510035c8-9316-11e7-845b-e95613cdaa3a.png)

**Comment by anthonydillon** [comment]
I favourite is 0001. Clear there is two different options and gives us room
to describe what the user can do with them.

**Comment by kwm14** [comment]
## Visual review

Meeting [notes](https://github.com/ubuntudesign/meeting-notes/issues/177) from our weekly visual review.

- All agreed 002 or 004 resources style was the best

Moving forward I need to create content and add to our existing Vanilla website doc for copy review before design progresses.

**Comment by kwm14** [comment]
## Visual exploration

- updated designs with signed-off content
- new variations taking influence from previous review

### 005
![downloads-001](https://user-images.githubusercontent.com/17748020/33140831-1912ba80-cfa9-11e7-98c4-504867c2d423.png)

### 006
![downloads-002](https://user-images.githubusercontent.com/17748020/33140832-19391108-cfa9-11e7-8db0-db50d31f6d85.png)

### 007
![downloads-003](https://user-images.githubusercontent.com/17748020/33140833-19633b54-cfa9-11e7-8ce7-51d6089389e5.png)

### 008
![downloads-004](https://user-images.githubusercontent.com/17748020/33140834-198e785a-cfa9-11e7-9e28-7981f6553258.png)

**Comment by anthonydillon** [comment]
005 or 007 has my vote.

**Comment by kwm14** [comment]
## Visual review

Meeting with @spencerbygraves to review designs.

- Version 007 preferred design +1
- Update button to link style seen in Version 005
- Align both CTA buttons to bottom?
- Add more padding between both section currently sitting quite close

**Comment by kwm14** [comment]
## Visual exploration

- updated design based on review feedback
- plus future design to include React once this epic of work is complete
- @spencerbygraves ready for re-review

### 009
![downloads-009](https://user-images.githubusercontent.com/17748020/33171364-b77f8db6-d043-11e7-8172-c275e9fde833.png)

### 009 with React
![downloads-react-009](https://user-images.githubusercontent.com/17748020/33171410-e7262c0a-d043-11e7-9abf-5f81a8103602.png)

**Comment by kwm14** [comment]
I've created an issue for this section to be built and added to vf.io [here](https://github.com/canonical-websites/vanillaframework.io/issues/101). Closing issue.
