### ISSUE TITLE
Missing: pagination navigation pattern

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-design#8]
Whilst working on build.snapcraft.io I've needed a pattern to navigate between lists of GitHub repos. There isn't, as far as I can see, a pattern for this. 

I'm going to work on one, based on the breadcrumb styling and see how I get on.

**Comment by jamiedawsonyoung** [comment]
Realise this should be a proper proposal to the VWG (Vanilla Working Group) and I'll do that when I've got time. This issue is just so I don't forget…

**Comment by yaili** [comment]
Thanks, @jamiedawsonyoung 

This is somewhat related to this I suppose: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/issues/17

@spencerbygraves @kwm14 has there been any pagination pattern designed in MAAS or Juju in the meantime?

**Comment by jamiedawsonyoung** [comment]
Yep, I'd say we need pagination for exactly the reason listed in the issue linked above. I made a stab at it for build.snapcraft.io It's just based on text styles and trying a lighter version of the vertical divider. See what you think. I will submit it properly as well.

![pagination-proposal](https://cloud.githubusercontent.com/assets/6909617/23499829/9b7b7bce-ff25-11e6-8bde-06a146540605.png)

**Comment by spencerbygraves** [comment]
No, nothing in Juju or MAAS at the moment.

**Comment by yaili** [comment]
So, if we follow our [process diagram](https://coggle.it/diagram/V0hkiP976OIbGpy8) there are two themes (brochure and dashboard) which would need a pagination pattern. Is that right? If so, that would warrant adding it to Vanilla base. Could I have some +1s on that? or -1s…

**Comment by anthonydillon** [comment]
We now have a pagination pattern in Vanilla: https://docs.vanillaframework.io/en/patterns/pagination
