### ISSUE TITLE
Change header to have a white background

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-design#87]
Following [our work](https://github.com/canonical-websites/snapcraft-flask/pull/23) to unify the header in snapcraft-flask with https://snapcraft.io, @spencerbygraves flagged that he would prefer that the unbranded Vanilla styling had a white header.

Could we change it? Is this okay for all existing properties with unbranded headers?

**Comment by kwm14** [comment]
@nottrobin had a review with @spencerbygraves and we've agreed to update our [Light navigation](https://docs.vanillaframework.io/en/patterns/navigation#light-navigation) to `$color-x-light`
