### ISSUE TITLE
New pattern: vf-p-social-icons

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-design#88]
A list of social icons for the footer, which looks like this:

![social-icons](https://user-images.githubusercontent.com/519935/30206522-3e533b2c-9484-11e7-93a2-b2ad21c8df7e.png)

Three different website projects now use effectively the same "social icons" list in the footer:

- [snapcraft.io](https://github.com/canonical-websites/snapcraft.io) (https://snapcraft.io)
- [build.snapcraft.io](https://github.com/canonical-websites/build.snapcraft.io) (https://build.snapcraft.io/)
- The new [snapcraft-flask](https://github.com/canonical-websites/snapcraft-flask/) app (http://snapcraft-flask-pr-32.run.demo.haus/dwarf-fortress/)

@bartaz did what I consider a very clean implementation of this locally to the `snapcraft-flask` project:

https://github.com/canonical-websites/snapcraft-flask/blob/master/static/sass/_patterns_social-icons.scss

Could this be a candidate for inclusion in Vanilla-framework?

**Comment by bartaz** [comment]
Also https://www.ubuntu.com/ has similar pattern in the footer.

**Comment by bartaz** [comment]
In theory these are simply an icons, so maybe they could be a part of Vanilla Icons pattern.

The biggest difference is that these icons are meant to be links with hover state in contrary to static icons that are currently in Vanilla.

**Comment by kwm14** [comment]
Thanks @nottrobin @bartaz for proposing this new component.

We have this piece of work scheduled for blog theme components [here](https://github.com/ubuntudesign/vanilla-squad/issues/49) and will be worked on when time is scheduled.

**Comment by nottrobin** [comment]
@kwm14 by closing this I think you risk losing the work @bartaz has done. We need a way to make sure that when someone has done a local implementation of a pattern, it doesn't simply get reimplemented when it goes into Vanilla. That's quite a waste.
