### ISSUE TITLE
New modifier: p-inline-list--compact

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-design#89]
Though @bartaz's work on [the social-icons pattern](https://github.com/ubuntudesign/vanilla-design/issues/88), he realised that the standard `2rem` margin above `p-inline-list` was simply too much space for this particular list.

So he created `p-inline-list--compact` which only has `1rem` of margin above it:

https://github.com/canonical-websites/snapcraft-flask/blob/master/static/sass/_patterns_inline-list--compact.scss

What is design's opinion of the `1rem` spacing? Is this the right way to solve this? Could it be included in vanilla core?

**Comment by kwm14** [comment]
Reference original design spec and vertical spacing.

**Comment by kwm14** [comment]
Discussed with @bartaz 
- Previously lists would have some big top margin, it's gone in new Vanilla v1.7 spacing changes 👍
