### ISSUE TITLE
Missing: spec / style for disabled links

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-design#9]
I might be being stupid but I can't see a style for a disabled link in the spec. I've used 50% opacity in the meantime.

**Comment by yaili** [comment]
I'm not sure if that's a common pattern. HTML5 doesn't determine that links (anchor tags) can be disabled: https://www.w3.org/TR/html5/disabled-elements.html 

But I might be missing some specific use case that would require that.

Any thoughts? @barrymcgee @anthonydillon @nottrobin

**Comment by anthonydillon** [comment]
I havn't seen a use case for a disabled link.

**Comment by barrymcgee** [comment]
I think this in an invalid use case, disabled states should be elements listed in the HTML spec only: (4.13) https://www.w3.org/TR/html5/disabled-elements.html
