### ISSUE TITLE
Vanilla's default header to full width

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-design#90]
As was recently brought to my attention, many of our modern sites (https://maas.io, https://landscape.canonical.com, https://jujucharms.com) have full-width headers:

![header](https://user-images.githubusercontent.com/519935/30207957-59b226f8-9489-11e7-882c-93443de5b1fc.png)

This is different from https://vanillaframework.io, as well as https://www.ubuntu.com and https://www.canonical.com:

![header2](https://user-images.githubusercontent.com/519935/30207976-75148f26-9489-11e7-8849-5d4af92d4b95.png)

If the full-width version represents the more modern design thinking, as I believe it now does, then should the Vanilla default be for it to be full-width - and subsequently to implement it this way on https://vanillaframework.io? (While still supporting the alternative)

**Comment by bartaz** [comment]
I suppose it is currently possible (if navigation is not inside of `row` it will span across whole width), but it's not a documented use case.

So if we consider it supported we should document it and make sure it's a use case that we test.

**Comment by kwm14** [comment]
- Update example on documentation
- Reverse notification text
- Update 'Notes' to use notification pattern style
- Change vanillaframework.io to use default (take out row element)
