### ISSUE TITLE
Social icons and sharing

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#92]
@kwm14 commented on [Wed Aug 09 2017](https://github.com/ubuntudesign/vanilla-squad/issues/49)

- include set of social icons on Vanilla
- do we need social sharing links on blog posts?

---

@matthewpaulthomas commented on [Thu Aug 17 2017](https://github.com/ubuntudesign/vanilla-squad/issues/49#issuecomment-323023541)

build.snapcraft.io has links to social channels in the footer of every page:
![vanilla-squad 50 footer](https://user-images.githubusercontent.com/19801137/29405947-6e8dfc04-8337-11e7-914b-56f9679d90c8.png)

At the same time, we have a Copy button to copy the code for a status badge on the repo page in particular:
![vanilla-squad 50 bsi badge](https://user-images.githubusercontent.com/19801137/29406142-16d95cfa-8338-11e7-9417-01319c964f06.png)

And if there’s a successful build, there are buttons for “Copy command”, “Post to Twitter”, “Post to Facebook”, etc for installation instructions on the same page:
![vanilla-squad 50 bsi instructions](https://user-images.githubusercontent.com/19801137/29406213-55043478-8338-11e7-818d-3abcbc61a36b.png)

There are two problems with the current graphics:
- The “Post to Twitter” button looks exactly the same as the “Follow us” on Twitter button, which could be confusing.
- Copying, tweeting, etc are equivalent ways of sharing that text, but they have very different visual styles. (They’ve been [physically separated as a temporary workaround](https://github.com/canonical-websites/build.snapcraft.io/pull/924#issuecomment-322812584).)

Both of these problems could be solved by having:
- one visual style for “Share this”-type buttons, including Copy
- a separate visual style for “Follow us”-type buttons.

**Comment by nottrobin** [comment]
Whoever comes to implement this, please don't forget to consider @bartaz's implementation:

https://github.com/canonical-websites/snapcraft-flask/blob/master/static/sass/_patterns_social-icons.scss

As originally [mentioned here](https://github.com/ubuntudesign/vanilla-design/issues/88).

**Comment by anthonydillon** [comment]
List of icons:
- Twitter
- Facebook
- G+
- YouTube
- Instagram
- Canonical
- Ubuntu

**Comment by pmahnke** [comment]
I also borrowed Bartek's version, but with a more full svg for design.ubuntu.com.

![image](https://user-images.githubusercontent.com/441217/30733727-24465f2e-9f70-11e7-95ac-6c936ff6b57a.png)

**Comment by kwm14** [comment]
## Review of social icons across various websites

### ubuntu.com
- default grey
- brand colour on rollover
- 32 x 32px

![screen shot 2017-09-29 at 11 58 29](https://user-images.githubusercontent.com/17748020/31024666-d04dad7a-a50d-11e7-94a6-97e8f4e7e8f3.png)

### jujucharms.com
- default grey
- brand colour on rollover
- 31 x 31px

![screen shot 2017-09-29 at 11 45 34](https://user-images.githubusercontent.com/17748020/31024342-bdaf1ea2-a50c-11e7-91ed-fd14859b46a2.png)

### snapcraft.io and build.snapcraft.io
- social heading
- default grey
- brand colour on rollover
- 45 x 45px

![screen shot 2017-09-29 at 11 54 53](https://user-images.githubusercontent.com/17748020/31024489-3aee1cc4-a50d-11e7-944e-b451eebab703.png)

**Comment by kwm14** [comment]
## Research

Looking into brand resources for icons there are minor rules to some brands we have to adhere to:

**Instagram** - never show the glyph smaller than 29x29 pixels

**Facebook** - version of the logo that comes on a white box on blue or dark coloured backgrounds

**Twitter** - preferred that our logo is free of a container, but you’ll also find the options to use a circle, square, or square with rounded corners.

**Comment by spencerbygraves** [comment]
I prefer the follow us icons with a container. For share, I wonder if we should use the code snippet icon (below) rather than the copy icon, seeing as the text already says 'Copy command'.

![image.png](https://images.zenhubusercontent.com/593a90fb51aa2c305781077c/5644810d-5c53-4b62-8d69-e5d6fcfba64f)

**Comment by kwm14** [comment]
@spencerbygraves ok great I prefer icons in a container too.

In regards to 'Copy command' are you suggesting to use the '$' icon rather than the copy to clipboard icon you created?

**Comment by spencerbygraves** [comment]
@kwm14 Yes, I thought it would be worth trying.

**Comment by kwm14** [comment]
## Updated exploration

- referencing visual feedback from @spencerbygraves 

### 002 - 'Follow us' icon set
- circular container
- left aligned text

![social follow v3](https://user-images.githubusercontent.com/17748020/31332514-98472c98-acde-11e7-94c3-aac4ee42974e.png)

### 002 - 'Share this' icon set
- update to icon used for 'copy command'

![social share v2](https://user-images.githubusercontent.com/17748020/31332550-b6185fda-acde-11e7-99a7-342adc8d5bfb.png)

**Comment by kwm14** [comment]
Design spec added [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Icons) social-icons.
