### ISSUE TITLE
Article pagination

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#94]
@kwm14 commented on [Wed Aug 09 2017](https://github.com/ubuntudesign/vanilla-squad/issues/47)

- if we add pagination at bottom of article it should align with [documentation](https://github.com/ubuntudesign/vanilla-squad/issues/24) proposal created by @Greggless 
- UX/Design work needed for 'previous' and 'next'

**Comment by kwm14** [comment]
## Visual exporation

- design based on @Greggless documentation work [here](https://user-images.githubusercontent.com/23459065/28416084-7002473c-6d4a-11e7-8804-b386dad611bc.png)
- using 1030px grid to frame next/previous pagiantion
- @spencerbygraves thoughts on explorations?

### Pagination 001
- left/right chevron has 'base' button styling
- design has default and hover state

![pagination-v1](https://user-images.githubusercontent.com/17748020/31335635-49a40216-aceb-11e7-918c-7f0b1e33f73c.png)

### Pagination 002
- left/right chevron has 'neutral' button styling
- #666 colour value added to next/prev titles
- design has default and hover state
- divider line to highlight two interactions

![pagination-v2](https://user-images.githubusercontent.com/17748020/31335625-448f8516-aceb-11e7-8b4c-226d78ca7cf8.png)

### Pagination 003
- left/right chevron default icon styling
- 6-col container hover state

![pagination-v3](https://user-images.githubusercontent.com/17748020/31335621-410e7fc8-aceb-11e7-9f2a-84895e53071f.png)

**Comment by spencerbygraves** [comment]
@kwm14 I like the 6-col having a hover state in 003. Can we try the right alignment for text on the 'Next' step please, as in Greg's wireframe. I think that might be better.

**Comment by kwm14** [comment]
## Updated exporation

- updates based on Spencers feedback
- based on our design guidelines I thought we could only left align text?
- @spencerbygraves ready for design re-review

### Pagination 004
![pagination-v4](https://user-images.githubusercontent.com/17748020/31446835-6caac6d8-ae98-11e7-9d8f-c32a18287278.png)

**Comment by spencerbygraves** [comment]
👍 004

**Comment by kwm14** [comment]
Design spec added [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Pagination).
