### ISSUE TITLE
Author profile

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#95]
@kwm14 commented on [Wed Aug 09 2017](https://github.com/ubuntudesign/vanilla-squad/issues/46)

- round avatar
- variation or same as media object
- different avatar and font sizes depending of location
  - author page and article page/list

**Comment by kwm14** [comment]
## First exploration of author profile

- round avatar
- name and role
- styling taken from 'Media object'
- @spencerbygraves thoughts?

![vanilla-author-profile](https://user-images.githubusercontent.com/17748020/30989084-73645c92-a46a-11e7-9942-3d4c5d2ed186.png)

**Comment by spencerbygraves** [comment]
I think we probably need a quick review of image sizes. For example, how do these fit with the sizes used for media object, which are different to these for small and large versions.

We also have charm and snap detail pages.

**Comment by kwm14** [comment]
Agree with reviewing sizes.

The example I created was based on size and styling of our current media object, and yes we do need to cater for charm and snap detail pages.

Can you share with me those pages so I have a guide to follow? @spencerbygraves

**Comment by kwm14** [comment]
## Continued exploration

- Discussing with Spencer I explored sizes for small, medium and large screens to cater for profiles used on blogs, articles, snap and charm details pages
- Allowing for different content to be added whether it be location of versions
- I've also created examples showing the component in situ
- @spencerbygraves ready for another design review 💯 

### 002
![author profile v2](https://user-images.githubusercontent.com/17748020/31287805-719f3ad4-aaba-11e7-9e71-0997dbf2589e.png)

### 002 blog example
![blog-example](https://user-images.githubusercontent.com/17748020/31288102-7b3e7f2c-aabb-11e7-9e65-b34fbfeda076.png)

### 002 snap example
![snap-example](https://user-images.githubusercontent.com/17748020/31287895-bfb7af4e-aaba-11e7-952f-6a4c757397c1.png)

### 002 charm example
![charm-example](https://user-images.githubusercontent.com/17748020/31287900-c6ff737c-aaba-11e7-802a-93ce36fe1d32.png)

**Comment by spencerbygraves** [comment]
@kwm14 Looks good now it all ties together, and with media object too. Thanks.

**Comment by anthonydillon** [comment]
Is this author pattern distinct from the media object pattern? Seems like
we maybe be able to combine into a single profile pattern?

**Comment by kwm14** [comment]
@spencerbygraves great, thanks!

@anthonydillon the only distinct difference from the media pattern is the shape of image/icon is now circular and the content displayed. But I guess the user will decide what they want to display whether it be:

- Location
- Link
- Bio
- Date

We could combine the media object into profile as it uses the same code but would we have clear distinction of naming variables, as users may not go to the 'Profile' component to find a the 'Media object' to add location for example to a page...

Happy for you and @barrymcgee to make final decision on code implementation?

**Comment by kwm14** [comment]
Design spec added [here](https://github.com/ubuntudesign/vanilla-design/tree/master/Profile).
