### ISSUE TITLE
Blog homepage

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#96]
@kwm14 commented on [Wed Aug 09 2017](https://github.com/ubuntudesign/vanilla-squad/issues/45)

- homepage needs visual design
- reference: https://design.canonical.com/

**Comment by kwm14** [comment]
@anthonydillon first pass are we looking to just convert styles to Vanilla because I can do that? Or if we're planning on redesigning layout, content and design it would need to be a separate piece of work potentially for the web team...

Current design
![design.ubuntu.homepage.png](https://images.zenhubusercontent.com/593a661951aa2c30578102ca/1b6a622c-eae0-4309-bc4a-b7b9e8c23d1f)

**Comment by anthonydillon** [comment]
Yeah I agree it's another piece of work.

**Comment by kwm14** [comment]
Ok great.

I've added a link to this issue in our Vanilla migration [document](https://docs.google.com/spreadsheets/d/12l8Ndb0vd1WSA0BYnMrrzgZ7aTtfLvVaPDd2gzvhQNw/edit#gid=0) so it's tracked there, and we can pick this up again once we decide to migrate design.canonical.com to Vanilla.

Closing issue.
