### ISSUE TITLE
How do we display search results

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#97]
@kwm14 commented on [Wed Aug 09 2017](https://github.com/ubuntudesign/vanilla-squad/issues/44)

- search result: special class of article list
- bold (regular) for query text
- show ellipsis (not in brackets)
- spacing or colour (title link) to visually separate results
- dates should follow our copy style guide everywhere
- filtering too complex for now (e.g Insights)
- not include tags

**Comment by kwm14** [comment]
## Quick look at 'search results' across some of our blogs:

### design.canonical
- bold (regular) for query text
- searched in brackets
- spacing or colour (title link) visually separates results

![design ubuntu](https://user-images.githubusercontent.com/17748020/31395639-1f4b5f48-add9-11e7-9229-4ac9f0da3154.png)

### blog.canonical
- bold (regular) for query text
- searched in brackets
- divider line separates search from results

![blog canonical](https://user-images.githubusercontent.com/17748020/31395932-e66ac528-add9-11e7-81a5-bd39a0f19027.png)

### ubuntu.insights
- query text in search box
- search filter but too complex for now
- suru background visually separates results

![ubuntu insights](https://user-images.githubusercontent.com/17748020/31395998-192346c0-adda-11e7-9e9a-0df21be20e12.png)

**Comment by kwm14** [comment]
## First visual exploration

- looking at the options above and making search results more consistent
- no tags displayed
- filtering to complex at the moment
- separating hero to highlight found results
- date styling follows copy guidelines [here](https://wiki.canonical.com/Marketing/Style_guide#Dates) with added icon 
- clear divider lines to either break content and posts
- regular font weight used to highlight query text and brand colour for links

### Search results 001
![search-results-v1](https://user-images.githubusercontent.com/17748020/31437870-bc85ef6c-ae7e-11e7-8eb8-c6192d493d6d.png)

### Search results 002
![search-results-v2](https://user-images.githubusercontent.com/17748020/31437876-c5569290-ae7e-11e7-81b1-80b916ddf315.png)

### Search results 003
![search-results-v3](https://user-images.githubusercontent.com/17748020/31437885-cb620098-ae7e-11e7-8474-4658887a4670.png)

**Comment by spencerbygraves** [comment]
@kwm14 looking good.

Can we try a version without dividing lines, with each result more compact. That might allow us to show more results on screen. I prefer 1 and 2 in terms of link styles. Thanks.

**Comment by kwm14** [comment]
## Updated visual exploration

- making each result more compact
     - moving date and author onto one line
     - article post preview onto one line
- regular link style for author
- soft link style for article title
- grey background to add visual separation from homepage posts and search result posts
- @spencerbygraves removing dividing lines made it difficult to scan posts being that they're more compact now so I added them back in

### Search results 004
![search-results-v4](https://user-images.githubusercontent.com/17748020/31542037-67c984ee-b008-11e7-8bc9-4d5703214642.png)

**Comment by kwm14** [comment]
## Review

- _attendees_ @spencerbygraves @Lukewh 
- make author/date and blog post first line more compact
- +1 on dividing lines

**Comment by kwm14** [comment]
## Updated design

- space between blog post title and date/author element - `0.5rem`
- space between date/author and blog post first line element - `0.25rem`
- space between divining lines separating post results element - `1.5rem`

### Search results 006
![search-results-v6](https://user-images.githubusercontent.com/17748020/31676281-ff8a1fc4-b35e-11e7-8ac5-f8628ae7f55b.png)

**Comment by kwm14** [comment]
## Search results styling

- it can be assembled using existing components
- no need for a new design spec
- I will reference this issue when building/updating [insights.ubuntu.com](https://insights.ubuntu.com/?s=ubuntu)
