### ISSUE TITLE
Proposal for archive lists

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#99]
@kwm14 commented on [Wed Aug 09 2017](https://github.com/ubuntudesign/vanilla-squad/issues/42)

- archives could use accordion
- archives becomes accordion after certain number of years
- lists with titles: card with heading _(classification lists)_
- leave lists with icons out for now
- how do we show number of items (see Juju/MAAS - Tags)
- does colour of number change? brackets?
- no tag clouds
- tags are comma separated (see Juju/MAAS)

**Comment by kwm14** [comment]
### Tags used in MAAS and Juju are consistent:

**MAAS**

![screen shot 2017-10-10 at 12 00 43](https://user-images.githubusercontent.com/17748020/31383491-24f2e4fa-adb3-11e7-95c3-718371d6cb27.png)

**Juju**

![screen shot 2017-10-10 at 12 03 06](https://user-images.githubusercontent.com/17748020/31383500-2dbf1810-adb3-11e7-89cb-5474f04ee913.png)

**Comment by kwm14** [comment]
## Initial visual exploration

- three versions using existing components
    - accordion
    - sidebar
    - card with header
- removing the brackets made it look similar to a date
- varied link styles for each exploration
- @spencerbygraves thoughts on these proposals?

### Archive list 001
![archive-list-v1](https://user-images.githubusercontent.com/17748020/31392159-7310f934-add0-11e7-95c5-efb60dc3b126.png)

**Comment by spencerbygraves** [comment]
@kwm14 I prefer the accordion version, the others feel more suited to being placed on the right hand side of a page. I think we use blue links for lists in Vanilla.

**Comment by kwm14** [comment]
## Updated visual

- updated design based on @spencerbygraves feedback
- reference link style [guidelines](https://www.dropbox.com/sh/nflaq5u6rqvfd8n/AACyawWRtDHKUdFZp43uh41wa?dl=0&preview=Link+styles+Vanilla.png) for lists

### Archive list 002
![archive-list-v2](https://user-images.githubusercontent.com/17748020/31445443-f6b10a98-ae95-11e7-86f1-3f91a4406d90.png)

**Comment by kwm14** [comment]
### Speaking with @barrymcgee 

- I wasn't sure where it would live either under 'Accordion' or 'Lists' as it's a mix of both
- decided that it doesn't have to be a stand alone component
- it can be assembled using existing patterns, so it doesn't need a new design spec
- I will reference this issue when building for visual
